/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Dumping data for table `auth_subfield_structure`
--

-- delete from auth_subfield_structure;
LOCK TABLES `auth_subfield_structure` WRITE;

/*!40000 ALTER TABLE `auth_subfield_structure` DISABLE KEYS */;

INSERT INTO `auth_subfield_structure` 
(`authtypecode`, `tagfield`, `tagsubfield`, `liblibrarian`, `libopac`, `repeatable`, `mandatory`, `tab`, `authorised_value`, `value_builder`, `seealso`, `isurl`, `hidden`, `linkid`, `kohafield`, `frameworkcode`, `defaultvalue`)
 VALUES
('','000','@','cabeçalho','cabeçalho',0,1,0,NULL,NULL,NULL,0,0,0,'','',''),
('','001','@','identificador','identificador',0,1,0,'','','',0,0,0,'','',''),
('','005','@','identificador','identificador',0,0,0,'','','',0,0,0,'','',''),
('','015','@','ISADN','ISADN',0,0,0,'','','',0,0,0,'','',''),
('','035','a','Número de controlo do sistema','Número de controlo do sistema',0,0,0,'','','',0,-5,0,'','',''),
('','035','z','Número de controlo cancelado ou inválido','Número de controlo cancelado ou inválido',1,0,0,'','','',0,-5,0,'','',''),
('','100','a','Dados gerais','Dados gerais',0,1,1,'','','',0,-5,0,'','',''),
('','101','a','Código da língua','Código da língua',0,0,1,'','','',0,-5,0,'','',''),
('','102','a','Código do País','Código do País',1,0,1,'','','',0,-5,0,'','',''),
('','102','b','Código da Localidade','Código da Localidade',1,0,1,'','','',0,-5,0,'','',''),
('','106','a','Código (1 caracter)','Código (1 caracter)',0,0,1,'','','',0,-5,0,'','',''),
('','120','a','Código (1 caracter)','Código (1 caracter)',0,0,1,'','','',0,-5,0,'','',''),
('','123','d','Coordenadas: longitude ocidental','Coordenadas: longitude ocidental',0,0,1,'','','',0,-5,0,'','',''),
('','123','e','Coordenadas: latitude setentrional','Coordenadas: latitude setentrional',0,0,1,'','','',0,-5,0,'','',''),
('','123','f','Coordenadas: longitude oriental','Coordenadas: longitude oriental',0,0,1,'','','',0,-5,0,'','',''),
('','123','g','Coordenadas: latitude meridional','Coordenadas: latitude meridional',0,0,1,'','','',0,-5,0,'','',''),
('','150','a','Name Processing Data','Name Processing Data',0,0,1,'','','',0,-5,0,'','',''),
('','152','a','Cataloguing Rules','Cataloguing Rules',0,0,1,'','','',0,-5,0,'','',''),
('','152','b','Subject System','Subject System',0,0,1,'','','',0,-5,0,'','',''),
('','154','a','Title Processing Data','Title Processing Data',0,0,1,'','','',0,-5,0,'','',''),
('','160','a','Geographic Area Code','Geographic Area Code',1,0,1,'','','',0,-5,0,'','',''),
('','200','4','Relator Code','Relator Code',1,0,2,'','','',0,0,0,'','',''),
('','200','7','Script','Script',0,0,2,'','','',0,0,0,'','',''),
('','200','8','Language of Cataloguing','Language of Cataloguing',0,0,2,'','','',0,0,0,'','',''),
('','200','a','Entry Element','Entry Element',0,0,2,'','','',0,0,0,'','',''),
('','200','b','Part of Name Other than Entry Element','Part of Name Other than Entry Element',0,0,2,'','','',0,0,0,'','',''),
('','200','c','Additions to Name Other than Dates','Additions to Name Other than Dates',0,0,2,'','','',0,0,0,'','',''),
('','200','d','Roman Numerals','Roman Numerals',0,0,2,'','','',0,0,0,'','',''),
('','200','f','Dates','Dates',0,0,2,'','','',0,0,0,'','',''),
('','200','g','Expansion of Initials of Forename','Expansion of Initials of Forename',0,0,2,'','','',0,0,0,'','',''),
('','200','j','Form Subdivision','Form Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','200','x','Topical Subdivision','Topical Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','200','y','Geographical Subdivision','Geographical Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','200','z','Chronological Subdivision','Chronological Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','210','4','Relator Code','Relator Code',1,0,2,'','','',0,0,0,'','',''),
('','210','7','Script','Script',0,0,2,'','','',0,0,0,'','',''),
('','210','8','Language of Cataloguing','Language of Cataloguing',0,0,2,'','','',0,0,0,'','',''),
('','210','a','Entry Element','Entry Element',0,0,2,'','','',0,0,0,'','',''),
('','210','b','Subdivision','Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','210','c','Additions to Name or Qualifier','Additions to Name or Qualifier',1,0,2,'','','',0,0,0,'','',''),
('','210','d','Number of Meeting','Number of Meeting',0,0,2,'','','',0,0,0,'','',''),
('','210','e','Location of Meeting','Location of Meeting',0,0,2,'','','',0,0,0,'','',''),
('','210','f','Date of Meeting','Date of Meeting',0,0,2,'','','',0,0,0,'','',''),
('','210','g','Inverted Element','Inverted Element',0,0,2,'','','',0,0,0,'','',''),
('','210','h','Part of Name Other than Entry Element and Inverted Element','Part of Name Other than Entry Element and Inverted Element',0,0,2,'','','',0,0,0,'','',''),
('','210','j','Form Subdivision','Form Subdivision',0,0,2,'',NULL,'',0,0,0,'','',''),
('','210','x','Topical Subdivision','Topical Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','210','y','Geographical Subdivision','Geographical Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','210','z','Chronological Subdivision','Chronological Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','215','7','Script','Script',0,0,2,'','','',0,0,0,'','',''),
('','215','8','Language of Cataloguing','Language of Cataloguing',0,0,2,'','','',0,0,0,'','',''),
('','215','a','Entry Element','Entry Element',0,0,2,'','','',0,0,0,'','',''),
('','215','j','Form Subdivision','Form Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','215','x','Topical Subdivision','Topical Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','215','y','Geographical Subdivision','Geographical Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','215','z','Chronological Subdivision','Chronological Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','216','7','Script','Script',0,0,2,'','','',0,0,0,'','',''),
('','216','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,2,'','','',0,0,0,'','',''),
('','216','a','Entry Element','Entry Element',0,0,2,'','','',0,0,0,'','',''),
('','216','c','Qualification','Qualification',1,0,2,'','','',0,0,0,'','',''),
('','216','f','Dates','Dates',0,0,2,'','','',0,0,0,'','',''),
('','216','j','Form Subdivision','Form Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','216','x','Topical Subdivision','Topical Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','216','y','Geographical Subdivision','Geographical Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','216','z','Chronological Subdivision','Chronological Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','220','4','Relator Code','Relator Code',1,0,2,'','','',0,0,0,'','',''),
('','220','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,2,'','','',0,0,0,'','',''),
('','220','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,2,'','','',0,0,0,'','',''),
('','220','a','Entry Element','Entry Element',0,0,2,'','','',0,0,0,'','',''),
('','220','f','Dates','Dates',0,0,2,'','','',0,0,0,'','',''),
('','220','j','Form Subdivision','Form Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','220','x','Topical Subdivision','Topical Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','220','y','Geographical Subdivision','Geographical Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','220','z','Chronological Subdivision','Chronological Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','230','7','Script','Script',0,0,2,'','','',0,0,0,'','',''),
('','230','8','Language of Cataloguing','Language of Cataloguing',0,0,2,'','','',0,0,0,'','',''),
('','230','a','Entry Element','Entry Element',0,0,2,'','','',0,0,0,'','',''),
('','230','b','General Material Designation','General Material Designation',1,0,2,'','','',0,0,0,'','',''),
('','230','h','Number of Section or Part','Number of Section or Part',1,0,2,'','','',0,0,0,'','',''),
('','230','i','Name of Section or Part','Name of Section or Part',1,0,2,'','','',0,0,0,'','',''),
('','230','j','Form Subdivision','Form Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','230','k','Date of Publication','Date of Publication',0,0,2,'','','',0,0,0,'','',''),
('','230','l','Form Subheading','Form Subheading',0,0,2,'','','',0,0,0,'','',''),
('','230','m','Language (when Part of Heading)','Language (when Part of Heading)',0,0,2,'','','',0,0,0,'','',''),
('','230','n','Miscellaneous Information','Miscellaneous Information',0,0,2,'',NULL,'',0,0,0,'','',''),
('','230','q','Version (or Date of Version)','Version (or Date of Version)',0,0,2,'','','',0,0,0,'','',''),
('','230','r','Medium of Performance (for Music)','Medium of Performance (for Music)',1,0,2,'','','',0,0,0,'','',''),
('','230','s','Numeric Designation (for Music)','Numeric Designation (for Music)',1,0,2,'','','',0,0,0,'','',''),
('','230','u','Key (for Music)','Key (for Music)',0,0,2,'','','',0,0,0,'','',''),
('','230','w','Arranged Statement (for Music)','Arranged Statement (for Music)',0,0,2,'','','',0,0,0,'','',''),
('','230','x','Topical Subdivision','Topical Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','230','y','Geographical Subdivision','Geographical Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','230','z','Chronological Subdivision','Chronological Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','235','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,2,'','','',0,0,0,'','',''),
('','235','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,2,'','','',0,0,0,'','',''),
('','235','a','Collective Uniform Title','Collective Uniform Title',0,0,2,'','','',0,0,0,'','',''),
('','235','b','General Material Designation','General Material Designation',1,0,2,'','','',0,0,0,'','',''),
('','235','e','Collective Uniform Subtitle','Collective Uniform Subtitle',0,0,2,'','','',0,0,0,'','',''),
('','235','j','Form Subdivision','Form Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','235','k','Date of Publication','Date of Publication',0,0,2,'','','',0,0,0,'','',''),
('','235','m','Language (when Part of Heading)','Language (when Part of Heading)',0,0,2,'','','',0,0,0,'','',''),
('','235','r','Medium of Performance (for Music)','Medium of Performance (for Music)',1,0,2,'','','',0,0,0,'','',''),
('','235','s','Numeric Designation (for Music)','Numeric Designation (for Music)',1,0,2,'','','',0,0,0,'','',''),
('','235','u','Key (for Music)','Key (for Music)',0,0,2,'','','',0,0,0,'','',''),
('','235','w','Arranged Statement (for Music)','Arranged Statement (for Music)',0,0,2,'','','',0,0,0,'','',''),
('','235','x','Topical Subdivision','Topical Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','235','y','Geographical Subdivision','Geographical Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','235','z','Chronological Subdivision','Chronological Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','240','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,2,'','','',0,0,0,'','',''),
('','240','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,2,'','','',0,0,0,'','',''),
('','240','a','Entry Element','Entry Element',0,0,2,'','','',0,0,0,'','',''),
('','240','j','Form Subdivision','Form Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','240','t','Title','Title',0,0,2,'','','',0,0,0,'','',''),
('','240','x','Topical Subdivision','Topical Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','240','y','Geographical Subdivision','Geographical Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','240','z','Chronological Subdivision','Chronological Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','245','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,2,'','','',0,0,0,'','',''),
('','245','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,2,'','','',0,0,0,'','',''),
('','245','a','Entry Element','Entry Element',0,0,2,'','','',0,0,0,'','',''),
('','245','j','Form Subdivision','Form Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','245','t','Title','Title',0,0,2,'','','',0,0,0,'','',''),
('','245','x','Topical Subdivision','Topical Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','245','y','Geographical Subdivision','Geographical Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','245','z','Chronological Subdivision','Chronological Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','250','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,2,'','','',0,0,0,'','',''),
('','250','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,2,'','','',0,0,0,'','',''),
('','250','a','Topical Subject','Topical Subject',0,0,2,'','','',0,0,0,'','',''),
('','250','j','Form Subdivision','Form Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','250','x','Topical Subdivision','Topical Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','250','y','Geographical Subdivision','Geographical Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','250','z','Chronological Subdivision','Chronological Subdivision',0,0,2,'','','',0,0,0,'','',''),
('','260','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,2,'','','',0,0,0,'','',''),
('','260','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,2,'','','',0,0,0,'','',''),
('','260','a','Country','Country',0,0,2,'','','',0,0,0,'','',''),
('','260','b','State or Province, etc.','State or Province, etc.',0,0,2,'','','',0,0,0,'','',''),
('','260','c','County','County',0,0,2,'','','',0,0,0,'','',''),
('','260','d','City','City',0,0,2,'','','',0,0,0,'','',''),
('','280','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,2,'','','',0,0,0,'','',''),
('','280','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,2,'','','',0,0,0,'','',''),
('','280','a','Entry Element','Entry Element',0,0,2,'','','',0,0,0,'','',''),
('','280','j','Form Subdivision','Form Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','280','x','Topical Subdivision','Topical Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','280','y','Geographical Subdivision','Geographical Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','280','z','Chronological Subdivision','Chronological Subdivision',1,0,2,'','','',0,0,0,'','',''),
('','300','6','Interfield Linking Data','Interfield Linking Data',0,0,3,'','','',0,-5,0,'','',''),
('','300','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,3,'','','',0,-5,0,'','',''),
('','300','a','Information Note','Information Note',0,0,3,'','','',0,-5,0,'','',''),
('','305','6','Interfield Linking Data','Interfield Linking Data',0,0,3,'','','',0,-5,0,'','',''),
('','305','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,3,'','','',0,-5,0,'','',''),
('','305','a','Instruction Phrase','Instruction Phrase',1,0,3,'','','',0,-5,0,'','',''),
('','305','b','Heading Referred','Heading Referred',1,0,3,'','','',0,-5,0,'','',''),
('','310','6','Interfield Linking Data','Interfield Linking Data',0,0,3,'','','',0,-5,0,'','',''),
('','310','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,3,'','','',0,-5,0,'','',''),
('','310','a','Instruction Phrase','Instruction Phrase',0,0,3,'','','',0,-5,0,'','',''),
('','310','b','Heading Referred','Heading Referred',1,0,3,'','','',0,-5,0,'','',''),
('','320','6','Interfield Linking Data','Interfield Linking Data',0,0,3,'','','',0,-5,0,'','',''),
('','320','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,3,'',NULL,'',0,0,0,'','',''),
('','320','a','General Explanatory Reference Note','General Explanatory Reference Note',1,0,3,'','','',0,-5,0,'','',''),
('','356','6','Interfield Linking Data','Interfield Linking Data',0,0,3,'','','',0,-5,0,'','',''),
('','356','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,3,'','','',0,-5,0,'','',''),
('','356','a','Geographical Note','Geographical Note',0,0,3,'','','',0,-5,0,'','',''),
('','400','0','Instruction Phrase','Instruction Phrase',0,0,4,'','','',0,0,0,'','',''),
('','400','2','Subject System Code','Subject System Code',0,0,4,'','','',0,0,0,'','',''),
('','400','3','Authority Record Number','Authority Record Number',0,0,4,'','','',0,0,0,'','',''),
('','400','4','Relator Code','Relator Code',1,0,4,'','','',0,0,0,'','',''),
('','400','5','Tracing Control','Tracing Control',0,0,4,'','','',0,0,0,'','',''),
('','400','6','Interfield Linking Data','Interfield Linking Data',0,0,4,'','','',0,0,0,'','',''),
('','400','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,4,'','','',0,0,0,'','',''),
('','400','a','Entry Element','Entry Element',0,0,4,'','','',0,0,0,'','',''),
('','400','b','Part of Name Other than Entry Element','Part of Name Other than Entry Element',0,0,4,'','','',0,0,0,'','',''),
('','400','c','Additions to Name Other than Dates','Additions to Name Other than Dates',0,0,4,'','','',0,0,0,'','',''),
('','400','d','Roman Numerals','Roman Numerals',0,0,4,'','','',0,0,0,'','',''),
('','400','f','Dates','Dates',0,0,4,'','','',0,0,0,'','',''),
('','400','g','Expansion of Initials of Forename','Expansion of Initials of Forename',0,0,4,'','','',0,0,0,'','',''),
('','400','j','Form Subdivision','Form Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','400','x','Topical Subdivision','Topical Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','400','y','Geographical Subdivision','Geographical Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','400','z','Chronological Subdivision','Chronological Subdivision',0,0,4,'','','',0,0,0,'','',''),
('','410','0','Instruction Phrase','Instruction Phrase',0,0,4,'','','',0,0,0,'','',''),
('','410','2','sub','sub',0,0,4,'','','',0,0,0,'','',''),
('','410','3','Authority Record Number','Authority Record Number',0,0,4,'','','',0,0,0,'','',''),
('','410','4','Relator Code','Relator Code',1,0,4,'','','',0,0,0,'','',''),
('','410','5','Tracing Control','Tracing Control',0,0,4,'','','',0,0,0,'','',''),
('','410','6','Interfield Linking Data','Interfield Linking Data',0,0,4,'','','',0,0,0,'','',''),
('','410','7','scr','scr',0,0,4,'','','',0,0,0,'','',''),
('','410','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,4,'','','',0,0,0,'','',''),
('','410','a','Entry Element','Entry Element',0,0,4,'','','',0,0,0,'','',''),
('','410','b','Subdivision','Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','410','c','Additions to Name or Qualifier','Additions to Name or Qualifier',1,0,4,'','','',0,0,0,'','',''),
('','410','d','Number of Meeting and/or Part of Meeting','Number of Meeting and/or Part of Meeting',0,0,4,'','','',0,0,0,'','',''),
('','410','e','Location of Meeting','Location of Meeting',0,0,4,'','','',0,0,0,'','',''),
('','410','f','Date of Meeting','Date of Meeting',0,0,4,'','','',0,0,0,'','',''),
('','410','g','Inverted Element','Inverted Element',0,0,4,'','','',0,0,0,'','',''),
('','410','h','Part of Name Other than Entry Element and Inverted Element','Part of Name Other than Entry Element and Inverted Element',0,0,4,'','','',0,0,0,'','',''),
('','410','j','Form Subdivision','Form Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','410','x','Topical Subdivision','Topical Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','410','y','Geographical Subdivision','Geographical Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','410','z','Chronological Subdivision','Chronological Subdivision',0,0,4,'','','',0,0,0,'','',''),
('','415','0','Instruction Phrase','Instruction Phrase',0,0,4,'','','',0,0,0,'','',''),
('','415','2','Subject System Code','Subject System Code',0,0,4,'','','',0,0,0,'','',''),
('','415','3','Authority Record Number','Authority Record Number',0,0,4,'','','',0,0,0,'','',''),
('','415','5','Tracing Control','Tracing Control',0,0,4,'','','',0,0,0,'','',''),
('','415','6','Interfield Linking Data','Interfield Linking Data',0,0,4,'','','',0,0,0,'','',''),
('','415','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,4,'','','',0,0,0,'','',''),
('','415','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,4,'','','',0,0,0,'','',''),
('','415','a','Entry Element','Entry Element',0,0,4,'','','',0,0,0,'','',''),
('','415','j','Form Subdivision','Form Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','415','x','Topical Subdivision','Topical Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','415','y','Geographical Subdivision','Geographical Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','415','z','Chronological Subdivision','Chronological Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','416','0','Instruction Phrase','Instruction Phrase',0,0,4,'','','',0,0,0,'','',''),
('','416','2','Subject System Code','Subject System Code',0,0,4,'','','',0,0,0,'','',''),
('','416','3','Authority Record Number','Authority Record Number',0,0,4,'','','',0,0,0,'','',''),
('','416','5','Tracing Control','Tracing Control',0,0,4,'','','',0,0,0,'','',''),
('','416','6','Interfield Linking Data','Interfield Linking Data',0,0,4,'','','',0,0,0,'','',''),
('','416','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,4,'','','',0,0,0,'','',''),
('','416','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,4,'','','',0,0,0,'','',''),
('','416','a','Entry Element','Entry Element',0,0,4,'','','',0,0,0,'','',''),
('','416','c','Qualification','Qualification',1,0,4,'','','',0,0,0,'','',''),
('','416','f','Dates','Dates',0,0,4,'','','',0,0,0,'','',''),
('','416','j','Form Subdivision','Form Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','416','x','Topical Subdivision','Topical Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','416','y','Geographical Subdivision','Geographical Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','416','z','Chronological Subdivision','Chronological Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','420','0','Instruction Phrase','Instruction Phrase',0,0,4,'','','',0,0,0,'','',''),
('','420','2','Subject System Code','Subject System Code',0,0,4,'','','',0,0,0,'','',''),
('','420','3','Authority Record Number','Authority Record Number',0,0,4,'','','',0,0,0,'','',''),
('','420','4','Relator Code','Relator Code',1,0,4,'','','',0,0,0,'','',''),
('','420','5','Tracing Control','Tracing Control',0,0,4,'','','',0,0,0,'','',''),
('','420','6','Interfield Linking Data','Interfield Linking Data',0,0,4,'','','',0,0,0,'','',''),
('','420','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,4,'','','',0,0,0,'','',''),
('','420','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,4,'',NULL,'',0,0,0,'','',''),
('','420','a','Entry Element','Entry Element',0,0,4,'','','',0,0,0,'','',''),
('','420','f','Dates','Dates',0,0,4,'','','',0,0,0,'','',''),
('','420','j','Form Subdivision','Form Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','420','x','Topical Subdivision','Topical Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','420','y','Geographical Subdivision','Geographical Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','420','z','Chronological Subdivision','Chronological Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','430','0','Instruction Phrase','Instruction Phrase',0,0,4,'','','',0,0,0,'','',''),
('','430','2','Subject System Code','Subject System Code',0,0,4,'','','',0,0,0,'','',''),
('','430','3','Authority Record Number','Authority Record Number',0,0,4,'','','',0,0,0,'','',''),
('','430','5','Tracing Control','Tracing Control',0,0,4,'','','',0,0,0,'','',''),
('','430','6','Interfield Linking Data','Interfield Linking Data',0,0,4,'','','',0,0,0,'','',''),
('','430','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,4,'','','',0,0,0,'','',''),
('','430','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,4,'','','',0,0,0,'','',''),
('','430','a','Entry Element','Entry Element',0,0,4,'','','',0,0,0,'','',''),
('','430','b','General Material Designation','General Material Designation',1,0,4,'','','',0,0,0,'','',''),
('','430','h','Number of Section or Part','Number of Section or Part',1,0,4,'','','',0,0,0,'','',''),
('','430','i','Name of Section or Part','Name of Section or Part',1,0,4,'','','',0,0,0,'','',''),
('','430','j','Form Subdivision','Form Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','430','k','Date of Publication','Date of Publication',0,0,4,'','','',0,0,0,'','',''),
('','430','l','Form Subheading','Form Subheading',0,0,4,'','','',0,0,0,'','',''),
('','430','m','Language (when Part of Heading)','Language (when Part of Heading)',0,0,4,'','','',0,0,0,'','',''),
('','430','n','Miscellaneous Information','Miscellaneous Information',0,0,4,'','','',0,0,0,'','',''),
('','430','q','Version (or Date of Version)','Version (or Date of Version)',0,0,4,'','','',0,0,0,'','',''),
('','430','r','Medium of Performance (for Music)','Medium of Performance (for Music)',1,0,4,'','','',0,0,0,'','',''),
('','430','s','Numeric Designation (for Music)','Numeric Designation (for Music)',1,0,4,'','','',0,0,0,'','',''),
('','430','u','Key (for Music)','Key (for Music)',0,0,4,'','','',0,0,0,'','',''),
('','430','w','Arranged Statement (for Music)','Arranged Statement (for Music)',0,0,4,'','','',0,0,0,'','',''),
('','430','x','Topical Subdivision','Topical Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','430','y','Geographical Subdivision','Geographical Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','430','z','Chronological Subdivision','Chronological Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','440','0','Instruction Phrase','Instruction Phrase',0,0,4,'','','',0,0,0,'','',''),
('','440','2','Subject System Code','Subject System Code',0,0,4,'','','',0,0,0,'','',''),
('','440','3','Authority Record Number','Authority Record Number',0,0,4,'','','',0,0,0,'','',''),
('','440','5','Tracing Control','Tracing Control',0,0,4,'','','',0,0,0,'','',''),
('','440','6','Interfield Linking Data','Interfield Linking Data',0,0,4,'','','',0,0,0,'','',''),
('','440','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,4,'','','',0,0,0,'','',''),
('','440','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,4,'','','',0,0,0,'','',''),
('','440','a','Entry Element','Entry Element',0,0,4,'','','',0,0,0,'','',''),
('','440','j','Form Subdivision','Form Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','440','t','Title','Title',0,0,4,'','','',0,0,0,'','',''),
('','440','x','Topical Subdivision','Topical Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','440','y','Geographical Subdivision','Geographical Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','440','z','Chronological Subdivision','Chronological Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','445','0','Instruction Phrase','Instruction Phrase',0,0,4,'','','',0,0,0,'','',''),
('','445','2','Subject System Code','Subject System Code',0,0,4,'','','',0,0,0,'','',''),
('','445','3','Authority Record Number','Authority Record Number',0,0,4,'','','',0,0,0,'','',''),
('','445','5','Tracing Control','Tracing Control',0,0,4,'','','',0,0,0,'','',''),
('','445','6','Interfield Linking Data','Interfield Linking Data',0,0,4,'','','',0,0,0,'','',''),
('','445','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,4,'','','',0,0,0,'','',''),
('','445','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,4,'','','',0,0,0,'','',''),
('','445','a','Entry Element','Entry Element',0,0,4,'','','',0,0,0,'','',''),
('','445','j','Form Subdivision','Form Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','445','t','Title','Title',0,0,4,'','','',0,0,0,'','',''),
('','445','x','Topical Subdivision','Topical Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','445','y','Geographical Subdivision','Geographical Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','445','z','Chronological Subdivision','Chronological Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','450','0','Instruction Phrase','Instruction Phrase',0,0,4,'','','',0,0,0,'','',''),
('','450','2','Subject System Code','Subject System Code',0,0,4,'','','',0,0,0,'','',''),
('','450','3','Authority Record Number','Authority Record Number',0,0,4,'','','',0,0,0,'','',''),
('','450','5','Tracing Control','Tracing Control',0,0,4,'','','',0,0,0,'','',''),
('','450','6','Interfield Linking Data','Interfield Linking Data',0,0,4,'','','',0,0,0,'','',''),
('','450','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,4,'','','',0,0,0,'','',''),
('','450','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,4,'','','',0,0,0,'','',''),
('','450','a','Entry Element','Entry Element',0,0,4,'','','',0,0,0,'','',''),
('','450','j','Form Subdivision','Form Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','450','x','Topical Subdivision','Topical Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','450','y','Geographical Subdivision','Geographical Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','450','z','Chronological Subdivision','Chronological Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','460','0','Instruction Phrase','Instruction Phrase',0,0,4,'','','',0,0,0,'','',''),
('','460','2','Subject System Code','Subject System Code',0,0,4,'','','',0,0,0,'','',''),
('','460','3','Authority Record Number','Authority Record Number',0,0,4,'','','',0,0,0,'','',''),
('','460','5','Tracing Control','Tracing Control',0,0,4,'','','',0,0,0,'','',''),
('','460','6','Interfield Linking Data','Interfield Linking Data',0,0,4,'','','',0,0,0,'','',''),
('','460','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,4,'','','',0,0,0,'','',''),
('','460','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,4,'','','',0,0,0,'','',''),
('','460','a','Country','Country',0,0,4,'','','',0,0,0,'','',''),
('','460','b','State or Province, etc.','State or Province, etc.',0,0,4,'','','',0,0,0,'','',''),
('','460','c','Country','Country',0,0,4,'','','',0,0,0,'','',''),
('','460','d','City','City',0,0,4,'','','',0,0,0,'','',''),
('','480','0','Instruction Phrase','Instruction Phrase',0,0,4,'','','',0,0,0,'','',''),
('','480','2','Subject System Code','Subject System Code',0,0,4,'','','',0,0,0,'','',''),
('','480','3','Authority Record Number','Authority Record Number',0,0,4,'','','',0,0,0,'','',''),
('','480','5','Tracing Control','Tracing Control',0,0,4,'','','',0,0,0,'','',''),
('','480','6','Interfield Linking Data','Interfield Linking Data',0,0,4,'','','',0,0,0,'','',''),
('','480','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,4,'','','',0,0,0,'','',''),
('','480','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,4,'','','',0,0,0,'','',''),
('','480','a','Entry Element','Entry Element',0,0,4,'','','',0,0,0,'','',''),
('','480','j','Form Subdivision','Form Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','480','x','Topical Subdivision','Topical Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','480','y','Geographical Subdivision','Geographical Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','480','z','Chronological Subdivision','Chronological Subdivision',1,0,4,'','','',0,0,0,'','',''),
('','500','0','Instruction Phrase','Instruction Phrase',0,0,5,'','','',0,0,0,'','',''),
('','500','2','Subject System Code','Subject System Code',0,0,5,'','','',0,0,0,'','',''),
('','500','3','Authority Record Number','Authority Record Number',0,0,5,'','','',0,0,0,'','',''),
('','500','4','Relator Code','Relator Code',1,0,5,'','','',0,0,0,'','',''),
('','500','5','Tracing Control','Tracing Control',0,0,5,'','','',0,0,0,'','',''),
('','500','6','Interfield Linking Data','Interfield Linking Data',0,0,5,'','','',0,0,0,'','',''),
('','500','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,5,'','','',0,0,0,'','',''),
('','500','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,5,'','','',0,0,0,'','',''),
('','500','a','Entry Element','Entry Element',0,0,5,'','','',0,0,0,'','',''),
('','500','b','Part of Name Other than Entry Element','Part of Name Other than Entry Element',0,0,5,'','','',0,0,0,'','',''),
('','500','c','Additions to Name Other than Dates','Additions to Name Other than Dates',1,0,5,'','','',0,0,0,'','',''),
('','500','d','Roman Numerals','Roman Numerals',0,0,5,'','','',0,0,0,'','',''),
('','500','f','Dates','Dates',0,0,5,'','','',0,0,0,'','',''),
('','500','g','Expansion of Initials of Forename','Expansion of Initials of Forename',0,0,5,'','','',0,0,0,'','',''),
('','500','j','Form Subdivision','Form Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','500','x','Topical Subdivision','Topical Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','500','y','Geographical Subdivision','Geographical Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','500','z','Chronological Subdivision','Chronological Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','510','0','Instruction Phrase','Instruction Phrase',0,0,5,'','','',0,0,0,'','',''),
('','510','2','Subject System Code','Subject System Code',0,0,5,'','','',0,0,0,'','',''),
('','510','3','Authority Record Number','Authority Record Number',0,0,5,'','','',0,0,0,'','',''),
('','510','4','Relator Code','Relator Code',1,0,5,'','','',0,0,0,'','',''),
('','510','5','Tracing Control','Tracing Control',0,0,5,'','','',0,0,0,'','',''),
('','510','6','Interfield Linking Data','Interfield Linking Data',0,0,5,'','','',0,0,0,'','',''),
('','510','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,5,'','','',0,0,0,'','',''),
('','510','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,5,'','','',0,0,0,'','',''),
('','510','a','Entry Element','Entry Element',0,0,5,'','','',0,0,0,'','',''),
('','510','b','Subdivision','Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','510','c','Additions to Name or Qualifier','Additions to Name or Qualifier',1,0,5,'','','',0,0,0,'','',''),
('','510','d','Number of Meeting and/or Part of Meeting','Number of Meeting and/or Part of Meeting',0,0,5,'','','',0,0,0,'','',''),
('','510','e','Location of Meeting','Location of Meeting',0,0,5,'','','',0,0,0,'','',''),
('','510','f','Date of Meeting','Date of Meeting',0,0,5,'','','',0,0,0,'','',''),
('','510','g','Inverted Element','Inverted Element',0,0,5,'','','',0,0,0,'','',''),
('','510','h','Part of Name Other than Entry Element and Inverted Element','Part of Name Other than Entry Element and Inverted Element',0,0,5,'','','',0,0,0,'','',''),
('','510','j','Form Subdivision','Form Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','510','x','Topical Subdivision','Topical Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','510','y','Geographical Subdivision','Geographical Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','510','z','Chronological Subdivision','Chronological Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','515','0','Instruction Phrase','Instruction Phrase',0,0,5,'','','',0,0,0,'','',''),
('','515','3','Authority Record Number','Authority Record Number',0,0,5,'','','',0,0,0,'','',''),
('','515','5','Tracing Control','Tracing Control',0,0,5,'','','',0,0,0,'','',''),
('','515','6','Interfield Linking Data','Interfield Linking Data',0,0,5,'','','',0,0,0,'','',''),
('','515','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,5,'','','',0,0,0,'','',''),
('','515','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,5,'','','',0,0,0,'','',''),
('','515','a','Entry Element','Entry Element',0,0,5,'','','',0,0,0,'','',''),
('','515','j','Form Subdivision','Form Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','515','x','Topical Subdivision','Topical Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','515','y','Geographical Subdivision','Geographical Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','515','z','Chronological Subdivision','Chronological Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','516','0','Instruction Phrase','Instruction Phrase',0,0,5,'','','',0,0,0,'','',''),
('','516','2','Subject System Code','Subject System Code',0,0,5,'','','',0,0,0,'','',''),
('','516','3','Authority Record Number','Authority Record Number',0,0,5,'','','',0,0,0,'','',''),
('','516','5','Tracing Control','Tracing Control',0,0,5,'','','',0,0,0,'','',''),
('','516','6','Interfield Linking Data','Interfield Linking Data',0,0,5,'','','',0,0,0,'','',''),
('','516','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,5,'','','',0,0,0,'','',''),
('','516','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,5,'','','',0,0,0,'','',''),
('','516','a','Entry Element','Entry Element',0,0,5,'','','',0,0,0,'','',''),
('','516','c','Qualification','Qualification',1,0,5,'','','',0,0,0,'','',''),
('','516','f','Dates','Dates',0,0,5,'','','',0,0,0,'','',''),
('','516','j','Form Subdivision','Form Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','516','x','Topical Subdivision','Topical Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','516','y','Geographical Subdivision','Geographical Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','516','z','Chronological Subdivision','Chronological Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','520','0','Instruction Phrase','Instruction Phrase',0,0,5,'','','',0,0,0,'','',''),
('','520','2','Subject System Code','Subject System Code',0,0,5,'','','',0,0,0,'','',''),
('','520','3','Authority Record Number','Authority Record Number',0,0,5,'','','',0,0,0,'','',''),
('','520','4','Relator Code','Relator Code',1,0,5,'','','',0,0,0,'','',''),
('','520','5','Tracing Control','Tracing Control',0,0,5,'','','',0,0,0,'','',''),
('','520','6','Interfield Linking Data','Interfield Linking Data',0,0,5,'','','',0,0,0,'','',''),
('','520','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,5,'','','',0,0,0,'','',''),
('','520','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,5,'','','',0,0,0,'','',''),
('','520','a','Entry Element','Entry Element',0,0,5,'','','',0,0,0,'','',''),
('','520','f','Dates','Dates',0,0,5,'','','',0,0,0,'','',''),
('','520','j','Form Subdivision','Form Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','520','x','Topical Subdivision','Topical Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','520','y','Geographical Subdivision','Geographical Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','520','z','Chronological Subdivision','Chronological Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','530','0','Instruction Phrase','Instruction Phrase',0,0,5,'','','',0,0,0,'','',''),
('','530','2','Subject System Code','Subject System Code',0,0,5,'','','',0,0,0,'','',''),
('','530','3','Authority Record Number','Authority Record Number',0,0,5,'','','',0,0,0,'','',''),
('','530','5','tra','tra',0,0,5,'','','',0,0,0,'','',''),
('','530','6','Interfield Linking Data','Interfield Linking Data',0,0,5,'','','',0,0,0,'','',''),
('','530','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,5,'','','',0,0,0,'','',''),
('','530','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,5,'','','',0,0,0,'','',''),
('','530','a','Entry Element','Entry Element',0,0,5,'','','',0,0,0,'','',''),
('','530','b','General Material Designation','General Material Designation',1,0,5,'','','',0,0,0,'','',''),
('','530','h','Number of Section or Part','Number of Section or Part',0,0,5,'','','',0,0,0,'','',''),
('','530','i','Name of Section or Part','Name of Section or Part',1,0,5,'','','',0,0,0,'','',''),
('','530','j','Form Subdivision','Form Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','530','k','Date de Publication','Date de Publication',0,0,5,'','','',0,0,0,'','',''),
('','530','l','Form Subheading','Form Subheading',0,0,5,'','','',0,0,0,'','',''),
('','530','m','Language (when Part of Heading)','Language (when Part of Heading)',0,0,5,'','','',0,0,0,'','',''),
('','530','n','Miscellaneous Information','Miscellaneous Information',1,0,5,'','','',0,0,0,'','',''),
('','530','q','Version (or Date of Version)','Version (or Date of Version)',0,0,5,'','','',0,0,0,'','',''),
('','530','r','Medium of Performance (for Music)','Medium of Performance (for Music)',1,0,5,'','','',0,0,0,'','',''),
('','530','s','Numeric Designation (for Music)','Numeric Designation (for Music)',1,0,5,'','','',0,0,0,'','',''),
('','530','u','Key (for Music)','Key (for Music)',0,0,5,'','','',0,0,0,'','',''),
('','530','w','Arranged Statement (for Music)','Arranged Statement (for Music)',0,0,5,'','','',0,0,0,'','',''),
('','530','x','Topical Subdivision','Topical Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','530','y','Geographical Subdivision','Geographical Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','530','z','Chronological Subdivision','Chronological Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','540','0','Instruction Phrase','Instruction Phrase',0,0,5,'','','',0,0,0,'','',''),
('','540','2','Subject System Code','Subject System Code',0,0,5,'','','',0,0,0,'','',''),
('','540','3','Authority Record Number','Authority Record Number',0,0,5,'','','',0,0,0,'','',''),
('','540','5','Tracing Control','Tracing Control',0,0,5,'','','',0,0,0,'','',''),
('','540','6','Interfield Linking Data','Interfield Linking Data',0,0,5,'','','',0,0,0,'','',''),
('','540','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,5,'','','',0,0,0,'','',''),
('','540','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,5,'','','',0,0,0,'','',''),
('','540','a','Entry Element','Entry Element',0,0,5,'','','',0,0,0,'','',''),
('','540','j','Form Subdivision','Form Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','540','t','Title','Title',0,0,5,'','','',0,0,0,'','',''),
('','540','x','Topical Subdivision','Topical Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','540','y','Geographical Subdivision','Geographical Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','540','z','Chronological Subdivision','Chronological Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','545','0','Instruction Phrase','Instruction Phrase',0,0,5,'','','',0,0,0,'','',''),
('','545','2','Subject System Code','Subject System Code',0,0,5,'','','',0,0,0,'','',''),
('','545','3','Authority Record Number','Authority Record Number',0,0,5,'','','',0,0,0,'','',''),
('','545','5','Tracing Control','Tracing Control',0,0,5,'','','',0,0,0,'','',''),
('','545','6','Interfield Linking Data','Interfield Linking Data',0,0,5,'','','',0,0,0,'','',''),
('','545','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,5,'','','',0,0,0,'','',''),
('','545','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,5,'','','',0,0,0,'','',''),
('','545','a','Entry Element','Entry Element',0,0,5,'','','',0,0,0,'','',''),
('','545','j','Form Subdivision','Form Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','545','t','Title','Title',0,0,5,'','','',0,0,0,'','',''),
('','545','x','Topical Subdivision','Topical Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','545','y','Geographical Subdivision','Geographical Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','545','z','Chronological Subdivision','Chronological Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','550','0','Instruction Phrase','Instruction Phrase',0,0,5,'','','',0,0,0,'','',''),
('','550','2','Subject System Code','Subject System Code',0,0,5,'','','',0,0,0,'','',''),
('','550','3','Authority Record Number','Authority Record Number',0,0,5,'','','',0,0,0,'','',''),
('','550','5','Tracing Control','Tracing Control',0,0,5,'','','',0,0,0,'','',''),
('','550','6','Interfield Linking Data','Interfield Linking Data',0,0,5,'','','',0,0,0,'','',''),
('','550','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,5,'','','',0,0,0,'','',''),
('','550','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,5,'','','',0,0,0,'','',''),
('','550','a','Entry Element','Entry Element',0,0,5,'','','',0,0,0,'','',''),
('','550','j','Form Subdivision','Form Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','550','x','Topical Subdivision','Topical Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','550','y','Geographical Subdivision','Geographical Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','550','z','Chronological Subdivision','Chronological Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','560','0','Instruction Phrase','Instruction Phrase',0,0,5,'','','',0,0,0,'','',''),
('','560','2','Subject System Code','Subject System Code',0,0,5,'','','',0,0,0,'','',''),
('','560','3','Authority Record Number','Authority Record Number',0,0,5,'','','',0,0,0,'','',''),
('','560','5','Tracing Control','Tracing Control',0,0,5,'','','',0,0,0,'','',''),
('','560','6','Interfield Linking Data','Interfield Linking Data',0,0,5,'','','',0,0,0,'','',''),
('','560','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,5,'','','',0,0,0,'','',''),
('','560','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,5,'','','',0,0,0,'','',''),
('','560','a','Country','Country',0,0,5,'','','',0,0,0,'','',''),
('','560','b','State or Province, etc.','State or Province, etc.',0,0,5,'','','',0,0,0,'','',''),
('','560','c','County','County',0,0,5,'','','',0,0,0,'','',''),
('','560','d','City','City',0,0,5,'','','',0,0,0,'','',''),
('','580','0','Instruction Phrase','Instruction Phrase',0,0,5,'','','',0,0,0,'','',''),
('','580','2','Subject System Code','Subject System Code',0,0,5,'','','',0,0,0,'','',''),
('','580','3','Authority Record Number','Authority Record Number',0,0,5,'','','',0,0,0,'','',''),
('','580','5','Tracing Control','Tracing Control',0,0,5,'','','',0,0,0,'','',''),
('','580','6','Interfield Linking Data','Interfield Linking Data',0,0,5,'','','',0,0,0,'','',''),
('','580','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,5,'','','',0,0,0,'','',''),
('','580','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,5,'','','',0,0,0,'','',''),
('','580','a','Entry Element','Entry Element',0,0,5,'','','',0,0,0,'','',''),
('','580','j','Form Subdivision','Form Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','580','x','Topical Subdivision','Topical Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','580','y','Geographical Subdivision','Geographical Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','580','z','Chronological Subdivision','Chronological Subdivision',1,0,5,'','','',0,0,0,'','',''),
('','675','3','Authority Code Number (Link to Classification Format)','Authority Code Number (Link to Classification Format)',0,0,6,'','','',0,-5,0,'','',''),
('','675','a','UDC Number, Single or Beginning of a Range','UDC Number, Single or Beginning of a Range',0,0,6,'','','',0,-5,0,'','',''),
('','675','b','UDC Number, End of a Range','UDC Number, End of a Range',0,0,6,'','','',0,-5,0,'','',''),
('','675','c','Explanatory Terms','Explanatory Terms',0,0,6,'','','',0,-5,0,'','',''),
('','675','v','UDC Edition','UDC Edition',0,0,6,'','','',0,-5,0,'','',''),
('','675','z','Language of Edition','Language of Edition',0,0,6,'','','',0,-5,0,'','',''),
('','676','3','Authority Code Number (Link to Classification Format)','Authority Code Number (Link to Classification Format)',0,0,6,'','','',0,-5,0,'','',''),
('','676','a','DDC Number, Single or Beginning of a Range','DDC Number, Single or Beginning of a Range',0,0,6,'','','',0,-5,0,'','',''),
('','676','b','DDC Number, End of a Range','DDC Number, End of a Range',0,0,6,'','','',0,-5,0,'','',''),
('','676','c','Explanatory Terms','Explanatory Terms',0,0,6,'','','',0,-5,0,'','',''),
('','676','v','DDC Edition','DDC Edition',0,0,6,'','','',0,-5,0,'','',''),
('','676','z','Language of Edition','Language of Edition',0,0,6,'','','',0,-5,0,'','',''),
('','680','3','Authority Code Number (Link to Classification Format)','Authority Code Number (Link to Classification Format)',0,0,6,'','','',0,-5,0,'','',''),
('','680','a','LC Number, Single or Beginning of a Range','LC Number, Single or Beginning of a Range',0,0,6,'','','',0,-5,0,'','',''),
('','680','b','LC Number, End of a Range','LC Number, End of a Range',0,0,6,'','','',0,-5,0,'','',''),
('','680','c','Explanatory Terms','Explanatory Terms',0,0,6,'','','',0,-5,0,'','',''),
('','686','2','Subject System Code','Subject System Code',0,0,6,'',NULL,'',0,0,0,'','',''),
('','686','a','Class Number, Single or Beginning of a Range','Class Number, Single or Beginning of a Range',0,0,6,'','','',0,-5,0,'','',''),
('','686','b','Class Number, End of a Range','Class Number, End of a Range',0,0,6,'','','',0,-5,0,'','',''),
('','686','c','Explanatory Terms','Explanatory Terms',0,0,6,'','','',0,-5,0,'','',''),
('','700','2','Subject System Code','Subject System Code',0,0,7,'','','',0,-5,0,'','',''),
('','700','3','Authority Record Number','Authority Record Number',0,0,7,'','','',0,-5,0,'','',''),
('','700','4','Relator Code','Relator Code',1,0,7,'','','',0,-5,0,'','',''),
('','700','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,7,'','','',0,-5,0,'','',''),
('','700','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,7,'','','',0,-5,0,'','',''),
('','700','a','Entry Element','Entry Element',0,0,7,'','','',0,-5,0,'','',''),
('','700','b','Part of Name Other than Entry Element','Part of Name Other than Entry Element',0,0,7,'','','',0,-5,0,'','',''),
('','700','c','Additions to Name Other than Dates','Additions to Name Other than Dates',0,0,7,'','','',0,-5,0,'','',''),
('','700','d','Roman Numerals','Roman Numerals',0,0,7,'','','',0,-5,0,'','',''),
('','700','f','Dates','Dates',0,0,7,'','','',0,-5,0,'','',''),
('','700','g','Expansion of Initials of Forename','Expansion of Initials of Forename',0,0,7,'','','',0,-5,0,'','',''),
('','700','j','Form Subdivision','Form Subdivision',1,0,7,'','','',0,-5,0,'','',''),
('','700','x','Topical Subdivision','Topical Subdivision',1,0,7,'','','',0,-5,0,'','',''),
('','700','y','Geographical Subdivision','Geographical Subdivision',1,0,7,'','','',0,-5,0,'','',''),
('','700','z','Chronological Subdivision','Chronological Subdivision',0,0,7,'','','',0,-5,0,'','',''),
('','710','2','Subject System Code','Subject System Code',0,0,7,'','','',0,-5,0,'','',''),
('','710','3','Authority Record Number','Authority Record Number',0,0,7,'','','',0,-5,0,'','',''),
('','710','4','Relator Code','Relator Code',1,0,7,'','','',0,-5,0,'','',''),
('','710','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,7,'','','',0,-5,0,'','',''),
('','710','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,7,'','','',0,-5,0,'','',''),
('','710','a','Entry Element','Entry Element',0,0,7,'','','',0,-5,0,'','',''),
('','710','b','Subdivision','Subdivision',1,0,7,'','','',0,-5,0,'','',''),
('','710','c','Additions to Name or Qualifier','Additions to Name or Qualifier',1,0,7,'','','',0,-5,0,'','',''),
('','710','d','Number of Meeting and/or Part of Meeting','Number of Meeting and/or Part of Meeting',0,0,7,'','','',0,-5,0,'','',''),
('','710','e','Location of Meeting','Location of Meeting',0,0,7,'','','',0,-5,0,'','',''),
('','710','f','Date of Meeting','Date of Meeting',0,0,7,'','','',0,-5,0,'','',''),
('','710','g','Inverted Element','Inverted Element',0,0,7,'','','',0,-5,0,'','',''),
('','710','h','Part of Name Other than Entry Element and Inverted Element','Part of Name Other than Entry Element and Inverted Element',0,0,7,'','','',0,-5,0,'','',''),
('','710','j','Form Subdivision','Form Subdivision',1,0,7,'','','',0,-5,0,'','',''),
('','710','x','Topical Subdivision','Topical Subdivision',1,0,7,'','','',0,-5,0,'','',''),
('','710','y','Geographical Subdivision','Geographical Subdivision',1,0,7,'','','',0,-5,0,'','',''),
('','710','z','Chronological Subdivision','Chronological Subdivision',0,0,7,'','','',0,-5,0,'','',''),
('','715','2','Subject System Code','Subject System Code',0,0,7,'','','',0,-5,0,'','',''),
('','715','3','Authority Record Number','Authority Record Number',0,0,7,'','','',0,-5,0,'','',''),
('','715','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,7,'','','',0,-5,0,'','',''),
('','715','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,7,'','','',0,-5,0,'','',''),
('','715','a','Entry Element','Entry Element',0,0,7,'','','',0,-5,0,'','',''),
('','715','j','Form Subdivision','Form Subdivision',1,0,7,'','','',0,-5,0,'','',''),
('','715','x','Topical Subdivision','Topical Subdivision',1,0,7,'','','',0,-5,0,'','',''),
('','715','y','Geographical Subdivision','Geographical Subdivision',1,0,7,'','','',0,-5,0,'','',''),
('','715','z','Chronological Subdivision','Chronological Subdivision',0,0,7,'','','',0,-5,0,'','',''),
('','716','2','Subject System Code','Subject System Code',0,0,7,'','','',0,-5,0,'','',''),
('','716','3','Authority Record Number','Authority Record Number',0,0,7,'','','',0,-5,0,'','',''),
('','716','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,7,'','','',0,-5,0,'','',''),
('','716','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,7,'','','',0,-5,0,'','',''),
('','716','a','Entry Element (Data Element)','Entry Element (Data Element)',0,0,7,'','','',0,-5,0,'','',''),
('','716','c','Qualification','Qualification',1,0,7,'','','',0,-5,0,'','',''),
('','716','f','Dates','Dates',0,0,7,'','','',0,-5,0,'','',''),
('','716','j','Form Subdivision','Form Subdivision',1,0,7,'','','',0,-5,0,'','',''),
('','716','x','Topical Subdivision','Topical Subdivision',1,0,7,'','','',0,-5,0,'','',''),
('','716','y','Geographical Subdivision','Geographical Subdivision',1,0,7,'','','',0,-5,0,'','',''),
('','716','z','Chronological Subdivision','Chronological Subdivision',0,0,7,'','','',0,-5,0,'','',''),
('','720','2','Subject System Code','Subject System Code',0,0,7,'','','',0,-5,0,'','',''),
('','720','3','Authority Record Number','Authority Record Number',0,0,7,'','','',0,-5,0,'','',''),
('','720','4','Relator Code','Relator Code',1,0,7,'','','',0,-5,0,'','',''),
('','720','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,7,'','','',0,-5,0,'','',''),
('','720','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,7,'','','',0,-5,0,'','',''),
('','720','a','Entry Element','Entry Element',0,0,7,'','','',0,-5,0,'','',''),
('','720','f','Dates','Dates',0,0,7,'','','',0,-5,0,'','',''),
('','720','j','Form Subdivision','Form Subdivision',1,0,7,'','','',0,-5,0,'','',''),
('','720','x','Topical Subdivision','Topical Subdivision',1,0,7,'','','',0,-5,0,'','',''),
('','720','y','Geographical Subdivision','Geographical Subdivision',1,0,7,'','','',0,-5,0,'','',''),
('','720','z','Chronological Subdivision','Chronological Subdivision',0,0,7,'','','',0,-5,0,'','',''),
('','730','2','Subject System Code','Subject System Code',0,0,7,'','','',0,-5,0,'','',''),
('','730','3','Authority Record Number','Authority Record Number',0,0,7,'','','',0,-5,0,'','',''),
('','730','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,7,'','','',0,-5,0,'','',''),
('','730','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,7,'','','',0,-5,0,'','',''),
('','730','a','Entry Element','Entry Element',0,0,7,'','','',0,-5,0,'','',''),
('','730','b','General Material Designation','General Material Designation',1,0,7,'','','',0,-5,0,'','',''),
('','730','h','Number of Section or Part','Number of Section or Part',1,0,7,'','','',0,-5,0,'','',''),
('','730','i','Name of Section or Part','Name of Section or Part',1,0,7,'','','',0,-5,0,'','',''),
('','730','j','Form Subdivision','Form Subdivision',1,0,7,'','','',0,-5,0,'','',''),
('','730','k','Date of Publication','Date of Publication',0,0,7,'','','',0,-5,0,'','',''),
('','730','l','Form Subheading','Form Subheading',0,0,7,'','','',0,-5,0,'','',''),
('','730','m','Language (when Part of Heading)','Language (when Part of Heading)',0,0,7,'','','',0,-5,0,'','',''),
('','730','n','Miscellaneous Information','Miscellaneous Information',0,0,7,'','','',0,-5,0,'','',''),
('','730','q','Version (or Date of Version)','Version (or Date of Version)',0,0,7,'','','',0,-5,0,'','',''),
('','730','r','Medium of Performance (for Music)','Medium of Performance (for Music)',1,0,7,'','','',0,-5,0,'','',''),
('','730','s','Numeric Designation (for Music)','Numeric Designation (for Music)',1,0,7,'','','',0,-5,0,'','',''),
('','730','u','Key (for Music)','Key (for Music)',0,0,7,'','','',0,-5,0,'','',''),
('','730','w','Arranged Statement (for Music)','Arranged Statement (for Music)',0,0,7,'','','',0,-5,0,'','',''),
('','730','x','Topical Subdivision','Topical Subdivision',1,0,7,'','','',0,-5,0,'','',''),
('','730','y','Geographical Subdivision','Geographical Subdivision',1,0,7,'','','',0,-5,0,'','',''),
('','730','z','Chronological Subdivision','Chronological Subdivision',0,0,7,'','','',0,-5,0,'','',''),
('','740','2','Subject System Code','Subject System Code',0,0,7,'','','',0,-5,0,'','',''),
('','740','3','Authority Record Number','Authority Record Number',0,0,7,'','','',0,-5,0,'','',''),
('','740','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,7,'','','',0,-5,0,'','',''),
('','740','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,7,'','','',0,-5,0,'','',''),
('','740','a','Entry Element','Entry Element',0,0,7,'','','',0,-5,0,'','',''),
('','740','j','Form Subdivision','Form Subdivision',1,0,7,'','','',0,-5,0,'','',''),
('','740','t','Title','Title',0,0,7,'','','',0,-5,0,'','',''),
('','740','x','Topical Subdivision','Topical Subdivision',1,0,7,'','','',0,-5,0,'','',''),
('','740','y','Geographical Subdivision','Geographical Subdivision',1,0,7,'','','',0,-5,0,'','',''),
('','740','z','Chronological Subdivision','Chronological Subdivision',0,0,7,'','','',0,-5,0,'','',''),
('','745','2','Subject System Code','Subject System Code',0,0,7,'','','',0,-5,0,'','',''),
('','745','3','Authority Record Number','Authority Record Number',0,0,7,'','','',0,-5,0,'','',''),
('','745','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,7,'','','',0,-5,0,'','',''),
('','745','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,7,'','','',0,-5,0,'','',''),
('','745','a','Entry Element','Entry Element',0,0,7,'','','',0,-5,0,'','',''),
('','745','j','Form Subdivision','Form Subdivision',1,0,7,'','','',0,-5,0,'','',''),
('','745','t','Title','Title',0,0,7,'','','',0,-5,0,'','',''),
('','745','x','Topical Subdivision','Topical Subdivision',1,0,7,'','','',0,-5,0,'','',''),
('','745','y','Geographical Subdivision','Geographical Subdivision',1,0,7,'','','',0,-5,0,'','',''),
('','745','z','Chronological Subdivision','Chronological Subdivision',0,0,7,'','','',0,-5,0,'','',''),
('','750','2','Subject System Code','Subject System Code',0,0,7,'','','',0,-5,0,'','',''),
('','750','3','Authority Record Number','Authority Record Number',0,0,7,'','','',0,-5,0,'','',''),
('','750','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,7,'','','',0,-5,0,'','',''),
('','750','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,7,'','','',0,-5,0,'','',''),
('','750','a','Entry Element','Entry Element',0,0,7,'','','',0,-5,0,'','',''),
('','750','j','Form Subdivision','Form Subdivision',1,0,7,'','','',0,-5,0,'','',''),
('','750','x','Topical Subdivision','Topical Subdivision',1,0,7,'','','',0,-5,0,'','',''),
('','750','y','Geographical Subdivision','Geographical Subdivision',1,0,7,'','','',0,-5,0,'','',''),
('','750','z','Chronological Subdivision','Chronological Subdivision',0,0,7,'','','',0,-5,0,'','',''),
('','760','2','Subject System Code','Subject System Code',0,0,7,'','','',0,-5,0,'','',''),
('','760','3','Authority Record Number','Authority Record Number',0,0,7,'','','',0,-5,0,'','',''),
('','760','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,7,'','','',0,-5,0,'','',''),
('','760','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,7,'','','',0,-5,0,'','',''),
('','760','a','Country','Country',0,0,7,'','','',0,-5,0,'','',''),
('','760','b','State or Province, etc.','State or Province, etc.',0,0,7,'','','',0,-5,0,'','',''),
('','760','c','County','County',0,0,7,'','','',0,-5,0,'','',''),
('','760','d','City','City',0,0,7,'','','',0,-5,0,'','',''),
('','780','2','Subject System Code','Subject System Code',0,0,7,'','','',0,-5,0,'','',''),
('','780','3','Authority Record Number','Authority Record Number',0,0,7,'','','',0,-5,0,'','',''),
('','780','7','Script of Cataloguing and Script of the Base Heading','Script of Cataloguing and Script of the Base Heading',0,0,7,'','','',0,-5,0,'','',''),
('','780','8','Language of Cataloguing and Language of the Base Heading','Language of Cataloguing and Language of the Base Heading',0,0,7,'','','',0,-5,0,'','',''),
('','780','a','Entry Element','Entry Element',0,0,7,'','','',0,-5,0,'','',''),
('','780','j','Form Subdivision','Form Subdivision',1,0,7,'','','',0,-5,0,'','',''),
('','780','x','Topical Subdivision','Topical Subdivision',1,0,7,'','','',0,-5,0,'','',''),
('','780','y','Geographical Subdivision','Geographical Subdivision',1,0,7,'','','',0,-5,0,'','',''),
('','780','z','Chronological Subdivision','Chronological Subdivision',0,0,7,'','','',0,-5,0,'','',''),
('','801','a','Country','Country',0,0,8,'','','',0,-5,0,'','',''),
('','801','b','Agency','Agency',0,0,8,'','','',0,-5,0,'','',''),
('','801','c','Date of Latest Transaction','Date of Latest Transaction',0,0,8,'','','',0,-5,0,'','',''),
('','810','a','Citation','Citation',0,0,8,'','','',0,-5,0,'','',''),
('','810','b','Information Found','Information Found',0,0,8,'','','',0,-5,0,'','',''),
('','815','a','Citation','Citation',1,0,8,'','','',0,-5,0,'','',''),
('','820','a','Note Text','Note Text',1,0,8,'','','',0,-5,0,'','',''),
('','825','a','Note Text','Note Text',0,0,8,'','','',0,-5,0,'','',''),
('','830','a','Note Text','Note Text',1,0,8,'','','',0,-5,0,'','',''),
('','835','a','Note Text','Note Text',1,0,8,'','','',0,-5,0,'','',''),
('','835','b','Replacement Heading','Replacement Heading',0,0,8,'','','',0,-5,0,'','',''),
('','835','d','Date of the Transaction','Date of the Transaction',0,0,8,'','','',0,-5,0,'','',''),
('','836','b','Replaced Heading','Replaced Heading',0,0,8,'','','',0,-5,0,'','',''),
('','836','d','Date of the Transaction','Date of the Transaction',0,0,8,'','','',0,-5,0,'','',''),
('','856','a','Host Name','Host Name',1,0,8,'','','',0,-5,0,'','',''),
('','856','b','Access Number','Access Number',1,0,8,'','','',0,-5,0,'','',''),
('','856','c','Compression Information','Compression Information',1,0,8,'','','',0,-5,0,'','',''),
('','856','d','Path','Path',1,0,8,'','','',0,-5,0,'','',''),
('','856','e','Date and Hour of Consultation and Access (YYYMMDDHHMM)','Date and Hour of Consultation and Access (YYYMMDDHHMM)',0,0,8,'','','',0,-5,0,'','',''),
('','856','f','Electronic Name','Electronic Name',1,0,8,'','','',0,-5,0,'','',''),
('','856','g','Uniform Resource Locator (URL)','Uniform Resource Locator (URL)',0,0,8,'','','',0,-5,0,'','',''),
('','856','h','Processor of Request','Processor of Request',0,0,8,'','','',0,-5,0,'','',''),
('','856','i','Instruction','Instruction',1,0,8,'','','',0,-5,0,'','',''),
('','856','j','Bits per Second','Bits per Second',0,0,8,'','','',0,-5,0,'','',''),
('','856','k','Password','Password',0,0,8,'','','',0,-5,0,'','',''),
('','856','l','Login/Logoff','Login/Logoff',0,0,8,'','','',0,-5,0,'','',''),
('','856','m','Contact for Access Assistance','Contact for Access Assistance',1,0,8,'','','',0,-5,0,'','',''),
('','856','n','Name of Location of Host in Subfield $a','Name of Location of Host in Subfield $a',0,0,8,'','','',0,-5,0,'','',''),
('','856','o','Operating System','Operating System',0,0,8,'','','',0,-5,0,'','',''),
('','856','p','Port','Port',0,0,8,'','','',0,-5,0,'','',''),
('','856','q','Electronic Format Type','Electronic Format Type',0,0,8,'','','',0,-5,0,'','',''),
('','856','r','Settings','Settings',0,0,8,'','','',0,-5,0,'','',''),
('','856','s','File Size','File Size',1,0,8,'','','',0,-5,0,'','',''),
('','856','t','Terminal Emulation','Terminal Emulation',1,0,8,'','','',0,-5,0,'','',''),
('','856','u','Uniform Address Locator (URL)','Uniform Address Locator (URL)',0,0,8,'','','',0,-5,0,'','',''),
('','856','v','Hours Access Method Available','Hours Access Method Available',1,0,8,'','','',0,-5,0,'','',''),
('','856','w','Record Control Number','Record Control Number',1,0,8,'','','',0,-5,0,'','',''),
('','856','x','Nonpublic Note','Nonpublic Note',0,0,8,'','','',0,-5,0,'','',''),
('','856','y','Access Method','Access Method',0,0,8,'','','',0,-5,0,'','',''),
('','856','z','Public Note','Public Note',1,0,8,'','','',0,-5,0,'','',''),
('','886','2','System Code','System Code',0,0,8,'','','',0,-5,0,'','',''),
('','886','a','Tag of the Source Format Field','Tag of the Source Format Field',1,0,8,'','','',0,-5,0,'','',''),
('','886','b','Indicators and Subfields of the Source Format Field','Indicators and Subfields of the Source Format Field',1,0,8,'','','',0,-5,0,'','',''),
('COR','000','@','cabeçalho','cabeçalho',0,1,0,'','marc21_leader_authorities.pl',NULL,0,0,0,'','',''),
('COR','001','@','identificador','identificador',0,0,0,'','',NULL,0,0,0,'','',''),
('COR','015','@','ISADN','ISADN',0,0,0,'','','',0,0,0,'','',''),
('COR','100','a','Dados gerais','Dados gerais',0,1,1,'','','',0,-5,0,'','',''),
('COR','101','a','Código da língua','Código da língua',0,0,1,'','','',0,-5,0,'','',''),
('COR','102','a','Código do País','Código do País',1,0,1,'','','',0,-5,0,'','',''),
('COR','152','a','Regras de catalogação','',0,0,1,'','',NULL,0,0,0,'','',''),
('COR','152','b','Sistema','Sistema',0,0,1,'','',NULL,0,0,0,NULL,'',''),
('COR','210','2','Código sistema indexação','',0,0,-1,'','',NULL,0,0,0,'','',''),
('COR','210','a','Palavra de ordem','Palavra de ordem',0,1,2,'','',NULL,0,0,0,NULL,'',''),
('COR','210','b','Subdivisão','Subdivisão',0,0,2,'','',NULL,0,0,0,NULL,'',''),
('COR','210','d','Número de congresso, reunião, etc...','',0,0,-1,'','',NULL,0,0,0,NULL,'',''),
('COR','210','e','Local de congresso, reunião, etc...','',0,0,-1,'','',NULL,0,0,0,NULL,'',''),
('COR','210','f','Data de congresso, reunião, etc...','',0,0,-1,'','',NULL,0,0,0,NULL,'',''),
('COR','210','z','Subdivisão cronológica','',0,0,-1,'','',NULL,0,0,0,NULL,'',''),
('COR','300','a','Texto da nota','Texto da nota',0,0,3,'','','',0,-5,0,'','',''),
('COR','320','a','Texto da nota','Texto da nota',1,0,3,'','','',0,-5,0,'','',''),
('COR','410','a','Palavra de ordem','Palavra de ordem',0,0,4,'','','',0,0,0,'','',''),
('COR','410','b','Subdivisão','Subdivisão',0,0,4,'','','',0,0,0,'','',''),
('COR','410','c','Elementos de distinção','Elementos de distinção',0,0,4,'','','',0,0,0,'','',''),
('COR','510','a','Palavra de ordem','Palavra de ordem',0,0,5,'','','',0,0,0,'','',''),
('COR','510','b','Subdivisão','Subdivisão',0,0,5,'','','',0,0,0,'','',''),
('COR','510','c','Elementos de distinção','Elementos de distinção',0,0,5,'','','',0,0,0,'','',''),
('COR','801','a','País','País',0,0,8,'','','',0,-5,0,'','',''),
('COR','801','b','Agência','Agência',0,0,8,'','','',0,-5,0,'','',''),
('COR','810','a','Citação','',0,0,-1,'','',NULL,0,0,0,'','',''),
('COR','810','b','Informação','',0,0,-1,'','',NULL,0,0,0,NULL,'',''),
('COR','830','a','Texto da nota','Texto da nota',1,0,8,'','','',0,-5,0,'','',''),
('COR','859','u','URL','',0,0,-1,'','',NULL,0,0,0,'','',''),
('COR','859','z','Nota informativa','',0,0,-1,'','',NULL,0,0,0,NULL,'',''),
('GEO','000','@','cabeçalho','cabeçalho',0,1,0,'','marc21_leader_authorities.pl',NULL,NULL,0,0,'','',NULL),
('GEO','001','@','identificador','identificador',0,0,0,'','',NULL,NULL,0,0,'','',NULL),
('GEO','015','@','ISADN','ISADN',0,0,0,'','','',NULL,0,0,'','',NULL),
('GEO','100','a','Dados gerais de processamento','',0,0,-1,'','',NULL,NULL,0,0,'','',NULL),
('GEO','101','a','Código da língua','Código da língua',0,0,1,'','','',NULL,-5,0,'','',NULL),
('GEO','102','a','Código do País','Código do País',1,0,1,'','','',NULL,-5,0,'','',NULL),
('GEO','152','a','Regras de catalogação','',0,0,1,'','',NULL,NULL,0,0,'','',NULL),
('GEO','152','b','Sistema','Sistema',0,0,1,'','',NULL,NULL,0,0,NULL,'',NULL),
('GEO','215','2','Código sistema indexação','',0,0,-1,'','',NULL,0,0,0,'','',''),
('GEO','215','a','Elemento de entrada','Elemento de entrada',0,0,-1,'','',NULL,0,0,0,NULL,'',''),
('GEO','215','x','Subdivisão assunto','',0,0,-1,'','',NULL,0,0,0,NULL,'',''),
('GEO','215','y','Subdivisão geográfica','',0,0,-1,'','',NULL,0,0,0,NULL,'',''),
('GEO','215','z','Subdivisão cronológica','',0,0,-1,'','',NULL,0,0,0,NULL,'',''),
('GEO','300','a','Nota informativa','',0,0,-1,'','',NULL,0,0,0,'','',''),
('GEO','320','a','Texto da nota','Texto da nota',1,0,3,'','','',NULL,-5,0,'','',NULL),
('GEO','415','a','Elemento de entrada','',0,0,-1,'','',NULL,0,0,0,'','',''),
('GEO','415','x','Subdivisão assunto','',0,0,-1,'','',NULL,0,0,0,NULL,'',''),
('GEO','415','y','Subdivisão geográfica','',0,0,-1,'','',NULL,0,0,0,NULL,'',''),
('GEO','515','a','Elemento de entrada','',1,0,-1,'','',NULL,0,0,0,'','',''),
('GEO','515','x','Subdivisão assunto','',0,0,-1,'','',NULL,0,0,0,NULL,'',''),
('GEO','515','y','Subdivisão geográfica','',0,0,-1,'','',NULL,0,0,0,NULL,'',''),
('GEO','675','a','Notação','',0,1,-1,'','',NULL,NULL,0,0,'','',NULL),
('GEO','675','c','Explicação textual','',0,1,-1,'','',NULL,NULL,0,0,NULL,'',NULL),
('GEO','675','v','Edição','',0,0,-1,'','',NULL,NULL,0,0,NULL,'',NULL),
('GEO','675','z','Língua','',0,0,-1,'','',NULL,NULL,0,0,NULL,'',NULL),
('GEO','801','a','País','País',0,0,8,'','','',NULL,-5,0,'','',NULL),
('GEO','801','b','Agência','Agência',0,0,8,'','','',NULL,-5,0,'','',NULL),
('GEO','830','a','Texto da nota','Texto da nota',1,0,8,'','','',NULL,-5,0,'','',NULL),
('GEO','856','x','Nota interna','Nota interna',0,0,8,'','','',NULL,-5,0,'','',NULL),
('GEO','856','z','Nota pública','Nota pública',1,0,8,'','','',NULL,-5,0,'','',NULL),
('GEO','859','u','URL','',0,0,-1,'','',NULL,0,0,0,'','',''),
('GEO','859','z','Nota informativa','',0,0,-1,'','',NULL,0,0,0,NULL,'',''),
('PER','000','@','Dados gerais','',0,0,0,'','marc21_leader_authorities.pl',NULL,0,0,0,'','',''),
('PER','001','@','Identificador do registo','Identificador do registo',0,0,0,'','',NULL,0,0,0,'','',''),
('PER','100','a','Dados gerais','Dados gerais',0,0,1,'','',NULL,0,0,0,'','',''),
('PER','101','a','Código da língua','Código da língua',0,0,1,'Lingua','',NULL,0,-5,0,'','',''),
('PER','102','a','Código do País','Código do País',0,0,1,'Pais','',NULL,0,-5,0,'','',''),
('PER','152','a','Regras de catalogação','',0,0,1,'','',NULL,0,0,0,'','',''),
('PER','152','b','Sistema','Sistema',0,0,1,'','',NULL,0,0,0,NULL,'',''),
('PER','200','a','Apelido','Apelido',0,0,2,'','',NULL,0,0,0,'','',''),
('PER','200','b','Nome','Nome',0,0,2,'','',NULL,0,0,0,NULL,'',''),
('PER','200','c','Elementos de identificação ou distinção','',0,0,2,'','',NULL,0,0,0,NULL,'',''),
('PER','200','f','Datas','Datas',0,0,2,'','',NULL,0,0,0,NULL,'',''),
('PER','300','a','Nota informativa','Nota informativa',0,0,3,'','',NULL,0,0,0,'','',''),
('PER','320','a','Texto da nota','Texto da nota',1,0,3,'','','',0,-5,0,'','',''),
('PER','400','a','Apelido','Apelido',0,0,4,'','','',0,0,0,'','',''),
('PER','400','b','Nome','Nome',0,0,4,'','','',0,0,0,'','',''),
('PER','400','f','Datas','Datas',0,0,4,'','','',0,0,0,'','',''),
('PER','500','a','Apelido','Apelido',0,0,5,'','','',0,0,0,'','',''),
('PER','500','b','Nome','Nome',0,0,5,'','','',0,0,0,'','',''),
('PER','500','f','Datas','Datas',0,0,5,'','','',0,0,0,'','',''),
('PER','675','a','Notação','',0,0,-1,'','',NULL,0,0,0,'','',''),
('PER','675','c','Explicação textual','',0,0,-1,'','',NULL,0,0,0,NULL,'',''),
('PER','675','v','Edição','',0,0,-1,'','',NULL,0,0,0,NULL,'','BN'),
('PER','675','z','Língua','',0,0,-1,'','',NULL,0,0,0,NULL,'','Português'),
('PER','801','a','País','País',0,0,8,'','','',0,-5,0,'','',''),
('PER','801','b','Agência','Agência',0,0,8,'','','',0,-5,0,'','',''),
('PER','810','a','Citação','',0,0,-1,'','',NULL,0,0,0,'','','VIAF'),
('PER','810','b','Informação','',0,0,-1,'','',NULL,0,0,0,NULL,'',''),
('PER','830','a','Texto da nota','Texto da nota',1,0,8,'','','',0,-5,0,'','',''),
('PER','856','x','Nota interna','Nota interna',0,0,8,'','','',0,-5,0,'','',''),
('PER','856','z','Nota pública','Nota pública',1,0,8,'','','',0,-5,0,'','',''),
('PER','859','u','URL','',0,0,-1,'','',NULL,0,0,0,'','',''),
('PER','859','z','Nota informativa','Nota informativa',0,0,-1,'','',NULL,0,0,0,NULL,'',''),
('SUB','000','@','cabeçalho','cabeçalho',0,1,0,'','marc21_leader_authorities.pl',NULL,0,0,0,'','',''),
('SUB','001','@','identificador','identificador',0,0,0,'','',NULL,0,0,0,'','',''),
('SUB','015','@','ISADN','ISADN',0,0,0,'','','',0,0,0,'','',''),
('SUB','100','a','Dados gerais de processamento','',0,0,-1,'','',NULL,0,0,0,'','',''),
('SUB','101','a','Código da língua','Código da língua',0,0,1,'','','',0,-5,0,'','',''),
('SUB','102','a','Código do País','Código do País',1,0,1,'','','',0,-5,0,'','',''),
('SUB','152','a','Regras de catalogação','',0,0,1,'','',NULL,0,0,0,'','',''),
('SUB','152','b','Sistema','Sistema',0,0,1,'','',NULL,0,0,0,NULL,'',''),
('SUB','250','2','Técnico responsável','',0,1,2,'','',NULL,0,0,0,'','',''),
('SUB','250','a','Assunto','Assunto',0,0,2,'','',NULL,0,0,0,NULL,'',''),
('SUB','250','j','Subdivisão de forma','',0,0,-1,'','',NULL,0,0,0,NULL,'',''),
('SUB','250','x','Subdivisão de assunto','Subdivisão de assunto',1,0,2,'','',NULL,0,0,0,NULL,'',''),
('SUB','250','y','Subdivisão geográfica','Subdivisão geográfica',0,0,2,'','',NULL,0,0,0,NULL,'',''),
('SUB','250','z','Subdivisão cronológica','Subdivisão cronológica',0,0,2,'','',NULL,0,0,0,NULL,'',''),
('SUB','320','a','Texto da nota','Texto da nota',1,0,3,'','','',0,-5,0,'','',''),
('SUB','450','a','Assunto','Assunto',0,0,4,'','','',0,0,0,'','',''),
('SUB','450','x','Subdivisão de assunto','Subdivisão de assunto',0,0,4,'','','',0,0,0,'','',''),
('SUB','450','y','Subdivisão geográfica','Subdivisão geográfica',0,0,4,'','','',0,0,0,'','',''),
('SUB','450','z','Subdivisão cronológica','Subdivisão cronológica',0,0,4,'','','',0,0,0,'','',''),
('SUB','550','a','Assunto','Assunto',0,0,5,'','','',0,0,0,'','',''),
('SUB','550','x','Subdivisão de assunto','Subdivisão de assunto',0,0,5,'','','',0,0,0,'','',''),
('SUB','550','y','Subdivisão geográfica','Subdivisão geográfica',0,0,5,'','','',0,0,0,'','',''),
('SUB','550','z','Datas','Datas',0,0,5,'','','',0,0,0,'','',''),
('SUB','675','a','Notação','',0,1,-1,'','',NULL,0,0,0,'','',''),
('SUB','675','c','Explicação textual','',0,1,-1,'','',NULL,0,0,0,NULL,'',''),
('SUB','675','v','Edição','',0,0,-1,'','',NULL,0,0,0,NULL,'','BN'),
('SUB','675','z','Língua','',0,0,-1,'','',NULL,0,0,0,NULL,'','Português'),
('SUB','801','a','País','País',0,0,8,'','','',0,-5,0,'','',''),
('SUB','801','b','Agência','Agência',0,0,8,'','','',0,-5,0,'','',''),
('SUB','830','a','Texto da nota','Texto da nota',1,0,8,'','','',0,-5,0,'','',''),
('SUB','856','x','Nota interna','Nota interna',0,0,8,'','','',0,-5,0,'','',''),
('SUB','856','z','Nota pública','Nota pública',1,0,8,'','','',0,-5,0,'','','')
on duplicate key update authtypecode=values(authtypecode), tagfield=values(tagfield), tagsubfield=values(tagsubfield), liblibrarian=values(liblibrarian), libopac=values(libopac), repeatable=values(repeatable), mandatory=values(mandatory), tab=values(tab), authorised_value=values(authorised_value), value_builder=values(value_builder), seealso=values(seealso), isurl=values(isurl), hidden=values(hidden), linkid=values(linkid), kohafield=values(kohafield), frameworkcode=values(frameworkcode), defaultvalue=values(defaultvalue);
/*!40000 ALTER TABLE `auth_subfield_structure` ENABLE KEYS */;
UNLOCK TABLES;

/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
