
/*!40101 SET NAMES utf8 */;
/*!40101 SET SQL_MODE=''*/;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

insert  into `authorised_values`
  (`id`, `category`, `authorised_value`, `lib`, `lib_opac`, `imageurl`)
 values 
 (1,'SUGGEST','BSELL','Bestseller',NULL,NULL),
 (2,'SUGGEST','SCD','Shelf Copy Damaged',NULL,NULL),
 (3,'SUGGEST','LCL','Library Copy Lost',NULL,NULL),
 (4,'SUGGEST','AVILL','Available via ILL',NULL,NULL),
 (5,'LOST','0','',NULL,NULL),
 (6,'LOST','2','Extraviado',NULL,NULL),
 (7,'LOST','1','Desaparecido',NULL,NULL),
 (8,'LOST','3','Desparecido e indeminizado',NULL,NULL),
 (9,'LOST','4','Em falta na estante',NULL,NULL),
 (10,'DAMAGED','0','',NULL,NULL),
 (11,'DAMAGED','1','Danificado',NULL,NULL),
 (12,'LOC','FIC','Fiction',NULL,NULL),
 (13,'LOC','Infantil','Zona infantil',NULL,NULL),
 (14,'LOC','Exposição','Em exposição',NULL,NULL),
 (15,'LOC','Novidades','Estante das novidades',NULL,NULL),
 (16,'LOC','Nos técnicos','gabinete dos técnicos',NULL,NULL),
 (17,'LOC','Em estante','Na estante',NULL,NULL),
 (18,'LOC','AV','Audio Visual',NULL,NULL),
 (19,'LOC','REF','Obras de referência',NULL,NULL),
 (20,'CCODE','FIC','Fiction',NULL,NULL),
 (21,'CCODE','REF','Reference',NULL,NULL),
 (22,'CCODE','NFIC','Non Fiction',NULL,NULL),
 (23,'WITHDRAWN','0','',NULL,NULL),
 (24,'WITHDRAWN','1','Withdrawn',NULL,NULL),
 (25,'NOT_LOAN','-1','Encomendado',NULL,''),
 (26,'NOT_LOAN','0','',NULL,NULL),
 (27,'NOT_LOAN','1','Não é permitido emprestar',NULL,''),
 (28,'NOT_LOAN','2','Restrito aos técnicos',NULL,''),
 (29,'RESTRICTED','0','',NULL,NULL),
 (30,'RESTRICTED','1','Acesso restrito',NULL,NULL),
 (31,'Pais','PT','Portugal',NULL,''),
 (32,'Lingua','por','Português',NULL,''),
 (33,'Tecnicos','Nome do técnico',NULL,NULL,''),
 (35,'Estado','ENC','Encomendado',NULL,''),
 (36,'Lingua','eng','Inglês',NULL,''),
 (37,'Lingua','ger','Alemão',NULL,''),
 (38,'Lingua','spa','Espanhol',NULL,''),
 (39,'Lingua','fre','Francês',NULL,''),
 (41,'Pais','FR','França',NULL,''),
 (42,'Pais','DE','Alemanha',NULL,''),
 (43,'Pais','ES','Espanha',NULL,''),
 (44,'Pais','GB','Reino Unido',NULL,''),
 (45,'Pais','US','Estados Unidos',NULL,''),
 (46,'Funcao','590','Intérprete',NULL,''),
 (47,'Funcao','070','Autor',NULL,''),
 (48,'Funcao','450','Autor da apresentação',NULL,''),
 (49,'Funcao','080','Autor da introdução',NULL,''),
 (50,'Funcao','030','Autor de arranjo musical',NULL,''),
 (51,'Funcao','340','Editor literário',NULL,''),
 (52,'Funcao','440','Ilustrador',NULL,''),
 (53,'Funcao','730','Tradutor',NULL,''),
 (54,'Tecnicos','Ana Raposo',NULL,NULL,''),
 (56,'Estado','CAN','Cancelado',NULL,''),
 (57,'Estado','COMP','Completo',NULL,''),
 (58,'Estado','DES','Desaparecido',NULL,''),
 (59,'Estado','PAR','Parcial',NULL,''),
 (60,'AQUISICAO','Compra','Compra',NULL,''),
 (61,'AQUISICAO','Oferta','Oferta',NULL,''),
 (62,'AQUISICAO','Permuta','Permuta',NULL,''),
 (63,'ASSINATURA','Activa','Activa',NULL,''),
 (64,'ASSINATURA','Inactiva','Inactiva',NULL,''),
 (65,'ASSINATURA','Suspensa','Suspensa',NULL,''),
 (66,'ASSINATURA','Cancelada','Cancelada',NULL,''),
 (67,'IGND','Registo sonoro','Registo sonoro',NULL,''),
 (68,'IGND','Registo vídeo','Registo vídeo',NULL,''),
 (69,'IGND','Música impressa','Música impressa',NULL,''),
 (70,'IGND','Documento electrónico','Documento electrónico',NULL,''),
 (71,'Pais','BR','Brasil',NULL,''),
 (72,'Pais','AR','Argentina',NULL,''),
 (73,'Tecnicos','Luísa Marques',NULL,NULL,''),
 (74,'Funcao','545','Músico',NULL,''),
 (75,'Funcao','200','Coreógrafo',NULL,''),
 (76,'Funcao','205','Colaborador',NULL,''),
 (77,'Funcao','000','Indeterminada (função)',NULL,''),
 (78,'Funcao','005','Actor',NULL,''),
 (79,'Funcao','010','Adaptador',NULL,''),
 (80,'Funcao','020','Anotador',NULL,''),
 (81,'Funcao','040','Artista',NULL,''),
 (82,'Funcao','050','Responsável editorial',NULL,''),
 (83,'Funcao','072','Autor em citações ou excertos de textos',NULL,''),
 (84,'Funcao','090','Autor do diálogo',NULL,''),
 (85,'Funcao','220','Compilador',NULL,''),
 (86,'Funcao','230','Compositor',NULL,''),
 (87,'Funcao','250','Maestro',NULL,''),
 (88,'Funcao','300','Director',NULL,''),
 (89,'Funcao','320','Doador',NULL,''),
 (90,'Funcao','370','Responsável pela montagem de filmes',NULL,''),
 (91,'Funcao','445','Empresário (teatral/musical)',NULL,''),
 (92,'Funcao','555','Arguente',NULL,''),
 (93,'Funcao','557','Organizador de conferência',NULL,''),
 (94,'Funcao','600','Fotógrafo',NULL,''),
 (95,'Funcao','630','Produtor',NULL,''),
 (96,'Funcao','632','Director artístico',NULL,''),
 (97,'Funcao','633','Equipa de produção',NULL,''),
 (98,'Funcao','690','Cenógrafo',NULL,''),
 (99,'Funcao','721','Cantor',NULL,''),
 (100,'Funcao','727','Orientador de tese',NULL,''),
 (101,'Funcao','640','Revisor',NULL,''),
 (102,'Lingua','it','Italiano',NULL,''),
 (103,'Pais','IT','Itália',NULL,''),
 (104,'Pais','MZ','Moçambique',NULL,''),
 (105,'Funcao','130','Responsável pela concepção gráfica do livro',NULL,''),
 (106,'Pais','MX','México',NULL,''),
 (107,'Pais','BE','Bélgica',NULL,''),
 (108,'Pais','CH','Suíça',NULL,''),
 (109,'Pais','VE','Venezuela',NULL,''),
 (110,'Funcao','695','Consultor científico',NULL,''),
 (111,'Funcao','240','Compositor gráfico',NULL,''),
 (112,'IGND','Programa de espectáculo','Programa de espectáculo',NULL,''),
 (113,'Pais','ARA','Árabe',NULL,''),
 (114,'Funcao','650','Editor comercial',NULL,''),
 (115,'Funcao','651','Director publicação',NULL,''),
 (116,'Pais','CA','Canadá',NULL,''),
 (117,'NOT_LOAN','3','Retirado temporariamente',NULL,''),
 (118,'NOT_LOAN','4','Extraviado',NULL,''),
 (119,'Pais','CU','Cuba',NULL,''),
 (120,'Funcao','560','Investigador',NULL,''),
 (121,'Pais','NL','Holanda',NULL,''),
 (122,'MANUAL_INV','Copier Fees','.25',NULL,NULL),
 (123,'BOR_NOTES','ADDR','Address Notes',NULL,NULL),
 (124,'LOC','CART','Book Cart',NULL,NULL),
 (125,'LOC','PROC','Processing Center',NULL,NULL),
 (126,'Bsort1','mestrado','Alunos de Mestrado',NULL,''),
 (127,'Bsort1','licenciado','alunos de licenciatura',NULL,'')
on duplicate key update id=values(id), category=values(category), authorised_value=values(authorised_value), lib=values(lib), lib_opac=values(lib_opac), imageurl=values(imageurl);
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;