/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES latin1 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Dumping data for table `marc_tag_structure`
--
delete from marc_tag_structure;
LOCK TABLES `marc_tag_structure` WRITE;

/*!40000 ALTER TABLE `marc_tag_structure` DISABLE KEYS */;

INSERT INTO `marc_tag_structure` VALUES ('000','Etiqueta do registo','Etiqueta do registo',0,1,'',''),
('001','Identificador do registo','Identificador do registo',0,0,'',''),
('005','Identificador da versão','Identificador da versão',0,0,'',''),
('010','Número internacional normalizado dos livros (ISBN)','Número internacional normalizado dos livros (ISBN)',1,0,'',''),
('011','Número internacional normalizado das publicações em série (ISSN) ','Número internacional normalizado das publicações em série (ISSN) ',1,0,'',''),
('012','Identificador da impressão ','Identificador da impressão',1,0,'',''),
('013','Número internacional normalizado da música (ISMN) ','Número internacional normalizado da música (ISMN) ',1,0,'',''),
('014','Identificador do artigo ','Identificador do artigo ',1,0,'',''),
('015','Número internacional normalizado para relatórios técnicos (ISRN) ','Número internacional normalizado para relatórios técnicos (ISRN) ',1,0,'',''),
('020','Número da bibliografia nacional','Número da bibliografia nacional',1,0,'',''),
('021','Número do Depósito Legal','Número do Depósito Legal',1,0,'',''),
('022','Número de publicação oficial ','Número de publicação oficial ',1,0,'',''),
('040','CODEN (Publicações em série) ','CODEN (Publicações em série) ',1,0,'',''),
('071','Número do editor (registos sonoros e música) ','Número do editor (registos sonoros e música) ',1,0,'',''),
('090','System Control Numbers (Koha)','System Control Numbers (Koha)',0,0,'',''),
('100','Dados gerais de processamento','Dados gerais de processamento',0,1,'',''),
('101','Língua de publicação','Língua de publicação',0,1,'Lingua',''),
('102','Pais de publicação ou produção','Pais de publicação ou produção',0,1,'Pais',''),
('105','Campo de dados codificados: livros','Campo de dados codificados: livros',0,0,'',''),
('106','Campo de dados codificados: material textual','Campo de dados codificados: material textual',0,0,'',''),
('110','Campo de dados codificados: Publicações em Série','Campo de dados codificados: Publicações em Série',0,0,'',''),
('115','Campo de dados codificados: Projecções Visuais, Filmes e Vídeos','Campo de dados codificados: Projecções Visuais, Filmes e Vídeos',1,0,'',''),
('116','Campo de dados codificados: Material Visual Gráfico','Campo de dados codificados: Material Visual Gráfico',1,0,'',''),
('117','Dados codificados artefactos a 3D e realia','Dados codificados artefactos a 3D e realia',1,0,'',''),
('120','Campo de dados codificados: Material Cartografico - Geral','Campo de dados codificados: Material Cartografico - Geral',0,0,'',''),
('121','Campo de dados codificados: Material Cartografico - Atributos Físicos','Campo de dados codificados: Material Cartografico - Atributos Físicos',0,0,'',''),
('122','Campo de dados codificados: Material Cartografico - Data de Posicionamento','Campo de dados codificados: Material Cartografico - Data de Posicionamento',1,0,'',''),
('123','Campo de dados codificados: Material Cartografico - Escala e Coordenadas','Campo de dados codificados: Material Cartografico - Escala e Coordenadas',1,0,'',''),
('124','Campo de dados codificados: Material Cartografico - Análise e Designação','Campo de dados codificados: Material Cartografico - Análise e Designação',0,0,'',''),
('125','Campo de dados codificados: Registos Sonoros e Música Impressa','Campo de dados codificados: Registos Sonoros e Música Impressa',0,0,'',''),
('126','Campo de dados codificados: Registos Sonoros - Atributos Físicos','Campo de dados codificados: Registos Sonoros - Atributos Físicos',0,0,'',''),
('127','Campo de dados codificados: Duração de Registos Sonoros e Música Impressa','Campo de dados codificados: Duração de Registos Sonoros e Música Impressa',0,0,'',''),
('128','Campo de dados codificados: Interpretações Musicais e Partituras','Campo de dados codificados: Interpretações Musicais e Partituras',1,0,'',''),
('130','Campo de dados codificados: Microformas - Atributos Físicos','Campo de dados codificados: Microformas - Atributos Físicos',1,0,'',''),
('131','Campo de dados codificados: Material Cartografico - Geodesia, Redes e Medidas Verticais','Campo de dados codificados: Material Cartografico - Geodesia, Redes e Medidas Verticais',0,0,'',''),
('135','Campo de dados codificados: Ficheiros de Computador','Campo de dados codificados: Ficheiros de Computador',0,0,'',''),
('140','Dados codificados de monografias antigas','Dados codificados de monografias antigas',0,0,'',''),
('141','Características específicas do exemplar','Características específicas do exemplar',1,0,'',''),
('200','Titulo e menção de responsabilidade','Titulo e menção de responsabilidade',0,0,'',''),
('205','Menção da edição','Menção da edição',1,0,'',''),
('206','Material Cartográfico - Dados matemáticos','Material Cartográfico - Dados matemáticos',1,0,'',''),
('207','Publicações em Série - Numeração','Publicações em Série - Numeração',0,0,'',''),
('208','Música impressa','Música impressa',0,0,'',''),
('210','Publicação, Distribuição, etc. ','Publicação, Distribuição, etc. ',1,0,'',''),
('215','Descrição física ','Descrição física ',1,0,'',''),
('225','Coleção ','Coleção ',1,0,'',''),
('230','Zona específica de alguns tipos de materiais: ficheiros de computador ','Zona específica de alguns tipos de materiais: ficheiros de computador ',1,0,'',''),
('300','Notas gerais ','Notas gerais ',1,0,'',''),
('301','Notas relativas a números de identificação ','Notas relativas a números de identificação ',1,0,'',''),
('302','Notas relativas a informação codificada ','Notas relativas a informação codificada ',1,0,'',''),
('303','Notas gerais relativas a informação descritiva ','Notas gerais relativas a informação descritiva ',1,0,'',''),
('304','Notas relativas a título e menção de responsabilidade ','Notas relativas a título e menção de responsabilidade ',1,0,'',''),
('305','Notas relativas à edição e história bibliográfica da publicação ','Notas relativas à edição e história bibliográfica da publicação ',1,0,'',''),
('306','Notas relativas a publicação, distribuição, etc. ','Notas relativas a publicação, distribuição, etc. ',1,0,'',''),
('307','Notas relativas a descrição física ','Notas relativas a descrição física ',1,0,'',''),
('308','Notas relativas à coleção','Notas relativas à coleção',1,0,'',''),
('310','Notas relativas à encadernação e modalidade de aquisição ','Notas relativas à encadernação e modalidade de aquisição ',1,0,'',''),
('311','Notas relativas a campos de entradas relacionadas ','Notas relativas a campos de entradas relacionadas ',1,0,'',''),
('312','Notas relativas a títulos relacionados ','Notas relativas a títulos relacionados ',1,0,'',''),
('313','Notas relativas a acesso por assunto ','Notas relativas a acesso por assunto ',1,0,'',''),
('314','Notas relativas a responsabilidade intelectual ','Notas relativas a responsabilidade intelectual ',1,0,'',''),
('315','Notas relativas a informação específica sobre alguns tipos de materiais (ou tipo de publicação)','Notas relativas a informação específica sobre alguns tipos de materiais (ou tipo de publicação)',1,0,'',''),
('316','Nota relativa ao exemplar catalogado (em mão) ','Nota relativa ao exemplar catalogado (em mão) ',1,0,'',''),
('317','Nota de proveniência ','Nota de proveniência ',1,0,'',''),
('318','Nota de intervenção ','Nota de intervenção ',1,0,'',''),
('320','Nota relativa a bibliografia e índices internos ','Nota relativa a bibliografia e índices internos ',1,0,'',''),
('321','Nota relativa a indíces, resumos de autor e referências externas ','Nota relativa a indíces, resumos de autor e referências externas ',1,0,'',''),
('322','Nota aos responsáveis artísticos e técnicos (material de projecção e video e registos sonoros) ','Nota aos responsáveis artísticos e técnicos (material de projecção e video e registos sonoros) ',0,0,'',''),
('323','Nota ao elenco (material de projeção e video de registos sonoros) ','Nota ao elenco (material de projeção e video de registos sonoros) ',1,0,'',''),
('324','Nota de versão original','Nota de versão original',0,0,'',''),
('325','Nota de reprodução','Nota de reprodução',1,0,'',''),
('326','Nota de periodicidade (publicações em série) ','Nota de periodicidade (publicações em série) ',1,0,'',''),
('327','Nota de conteúdo ','Nota de conteúdo ',1,0,'',''),
('328','Nota de dissertação ou tese','Nota de dissertação ou tese',1,0,'',''),
('330','Sumário ou Resumo','Sumário ou Resumo',1,0,'',''),
('332','Citação preferencial dos materiais descritos','Citação preferencial dos materiais descritos',1,0,'',''),
('333','Nota relativa aos potenciais utilizadores','Nota relativa aos potenciais utilizadores',1,0,'',''),
('334','Nota de prémios','Nota de prémios',1,0,'',''),
('336','Nota relativa ao tipo de ficheiro de computador (provisória) ','Nota relativa ao tipo de ficheiro de computador (provisória) ',1,0,'',''),
('337','Nota relativa a pormenores técnicos (recursos eletrónicos)','Nota relativa a pormenores técnicos (recursos eletrónicos)',1,0,'',''),
('345','Nota informativa sobre aquisição','Nota informativa sobre aquisição',0,0,'',''),
('410','Coleção','Coleção',1,0,'',''),
('411','Subcoleção','Subcoleção',1,0,'',''),
('421','Suplemento de','Suplemento de',1,0,'',''),
('422','Filiação do suplemento','Filiação do suplemento',1,0,'',''),
('423','Publicado com','Publicado com',1,0,'',''),
('430','Continua','Continua',1,0,'',''),
('431','Continua em parte','Continua em parte',1,0,'',''),
('432','Substitui','Substitui',1,0,'',''),
('433','Substitui em parte','Substitui em parte',1,0,'',''),
('434','Absorve','Absorve',1,0,'',''),
('435','Absorve em parte','Absorve em parte',1,0,'',''),
('436','Fusão de','Fusão de',1,0,'',''),
('437','Separado de','Separado de',1,0,'',''),
('440','Continuado por','Continuado por',1,0,'',''),
('441','Continuado em parte por','Continuado em parte por',1,0,'',''),
('442','Substituído por','Substituído por',1,0,'',''),
('443','Substituído em parte por','Substituído em parte por',1,0,'',''),
('444','Absorvido por','Absorvido por',1,0,'',''),
('445','Absorvido em parte por','Absorvido em parte por',1,0,'',''),
('446','Cindido em','Cindido em',1,0,'',''),
('447','Fundido com','Fundido com',1,0,'',''),
('448','Mudou de novo para','Mudou de novo para',1,0,'',''),
('451','Outra edição no mesmo suporte','Outra edição no mesmo suporte',1,0,'',''),
('452','Edição em suporte diferente','Edição em suporte diferente',1,0,'',''),
('453','Traduzido como','Traduzido como',1,0,'',''),
('454','Tradução de','Tradução de',1,0,'',''),
('455','Reprodução de','Reprodução de',1,0,'',''),
('456','Reproduzido como','Reproduzido como',1,0,'',''),
('461','Nível de conjunto','Nível de conjunto',1,0,'',''),
('462','Nível de subconjunto','Nível de subconjunto',1,0,'',''),
('463','Nível de parte','Nível de parte',1,0,'',''),
('464','Nível de parte analítica','Nível de parte analítica',1,0,'',''),
('470','Recensão de','Recensão de',1,0,'',''),
('481','Também encadernado neste volume','Também encadernado neste volume',1,0,'',''),
('482','Encadernado com','Encadernado com',1,0,'',''),
('488','Outras obras relacionadas','Outras obras relacionadas',1,0,'',''),
('500','Título Uniforme','Título Uniforme',1,0,'',''),
('501','Título colectivo uniforme','Título colectivo uniforme',1,0,'',''),
('503','Cabeçalho convencional uniforme','Cabeçalho convencional uniforme',1,0,'',''),
('510','Título paralelo','Título paralelo',1,0,'',''),
('512','Título da capa','Título da capa',1,0,'',''),
('513','Título de página de rosto complementar','Título de página de rosto complementar',1,0,'',''),
('514','Título de apresentação do texto','Título de apresentação do texto',1,0,'',''),
('515','Título corrente','Título corrente',1,0,'',''),
('516','Título da lombada','Título da lombada',1,0,'',''),
('517','Outras variantes do título','Outras variantes do título',1,0,'',''),
('518','Título na grafia actualizada','Título na grafia actualizada',1,0,'',''),
('520','Título anterior (publicações em série)','Título anterior (publicações em série)',1,0,'',''),
('530','Título chave (publicações em série)','Título chave (publicações em série)',1,0,'',''),
('531','Título abreviado (publicações em série) ','Título abreviado (publicações em série) ',1,0,'',''),
('532','Título desenvolvido','Título desenvolvido',1,0,'',''),
('540','Título adicionado pelo catalogador','Título adicionado pelo catalogador',1,0,'',''),
('541','Título traduzido pelo catalogador','Título traduzido pelo catalogador',1,0,'',''),
('545','Título da secção','Título da secção',1,0,'',''),
('600','Nome de pessoa usado como assunto','Nome de pessoa usado como assunto',1,0,'',''),
('601','Nome de colectividade usado como assunto','Nome de colectividade usado como assunto',1,0,'',''),
('602','Nome de família usado como assunto','Nome de família usado como assunto',1,0,'',''),
('604','Autor/título usado como assunto ','Autor/título usado como assunto ',1,0,'',''),
('605','Título usado como assunto','Título usado como assunto',1,0,'',''),
('606','Nome comum usado como assunto','Nome comum usado como assunto',1,0,'',''),
('607','Nome geográfico usado como assunto','Nome geográfico usado como assunto',1,0,'',''),
('608','Forma, género ou característica física','Forma, género ou característica física',1,0,'',''),
('610','Termos de indexação não controlados','Termos de indexação não controlados',1,0,'',''),
('615','Categoria de assunto','Categoria de assunto',1,0,'',''),
('620','Acesso pelo local','Acesso pelo local',1,0,'',''),
('626','Acesso por pormenores técnicos (ficheiros de computador) (provisório) ','Acesso por pormenores técnicos (ficheiros de computador) (provisório) ',1,0,'',''),
('660','Código da área geográfica','Código da área geográfica',1,0,'',''),
('661','Código do período de tempo','Código do período de tempo',1,0,'',''),
('670','PRECIS','PRECIS',1,0,'',''),
('675','Classificação Decimal Universal (CDU)','Classificação Decimal Universal (CDU)',1,0,'',''),
('676','Classificação Decimal Dewey (CDD)','Classificação Decimal Dewey (CDD)',1,0,'',''),
('680','Classificação da Biblioteca do Congresso','Classificação da Biblioteca do Congresso',1,0,'',''),
('686','Outras classificações numéricas','Outras classificações numéricas',1,0,'',''),
('700','Nome de autor-pessoa física (responsabilidade principal)','Nome de autor-pessoa física (responsabilidade principal)',0,0,'',''),
('701','Nome de autor-pessoa física (co-responsabilidade principal)','Nome de autor-pessoa física (co-responsabilidade principal)',1,0,'',''),
('702','Nome de autor-pessoa física (responsabilidade secundária)','Nome de autor-pessoa física (responsabilidade secundária)',1,0,'',''),
('710','Nome de colectividade-autor (responsabilidade principal)','Nome de colectividade-autor (responsabilidade principal)',0,0,'',''),
('711','Nome de colectividade-autor (co-responsabilidade principal)','Nome de colectividade-autor (co-responsabilidade principal)',1,0,'',''),
('712','Nome de colectividade-autor (responsabilidade secundária)','Nome de colectividade-autor (responsabilidade secundária)',1,0,'',''),
('720','Nome de família (responsabilidade principal)','Nome de família (responsabilidade principal)',0,0,'',''),
('721','Nome de família (co-responsabilidade principal)','Nome de família (co-responsabilidade principal)',1,0,'',''),
('722','Nome de família (responsabilidade secundária)','Nome de família (responsabilidade secundária)',1,0,'',''),
('801','Fonte de origem','Fonte de origem',1,0,'',''),
('802','Centro ISDS','Centro ISDS',0,0,'',''),
('830','Notas gerais do catalogador','Notas gerais do catalogador',1,0,'',''),
('852','Localização e cota','Localização e cota',1,0,'',''),
('856','Localização e acesso electrónico ','Localização e acesso electrónico ',1,0,'',''),
('990','Elementos KOHA','Elementos KOHA',0,0,'',''),
('994','Estado da catalogação','Estado da catalogação',0,0,'',''),
('995','Localização e informação dos exemplares','Localização e informação dos exemplares',1,1,'',''),
('000','Etiqueta do registo','Etiqueta do registo',0,1,'','AMN'),
('001','Identificador do registo','Identificador do registo',0,0,'','AMN'),
('005','Identificador da versão','Identificador da versão',0,0,'','AMN'),
('090','System Control Numbers (Koha)','System Control Numbers (Koha)',0,0,'','AMN'),
('100','Dados gerais de processamento','Dados gerais de processamento',0,1,'','AMN'),
('101','Língua de publicação','Língua de publicação',0,0,'Lingua','AMN'),
('102','Pais de publicação ou produção','Pais de publicação ou produção',0,0,'Pais','AMN'),
('200','Titulo e menção de responsabilidade','Titulo e menção de responsabilidade',0,0,'','AMN'),
('300','Notas gerais ','Notas gerais ',1,0,'','AMN'),
('305','Notas relativas à edição e história bibliográfica da publicação ','Notas relativas à edição e história bibliográfica da publicação ',1,0,'','AMN'),
('312','Notas relativas a títulos relacionados ','Notas relativas a títulos relacionados ',1,0,'','AMN'),
('313','Notas relativas a acesso por assunto','Notas relativas a acesso por assunto',1,0,'','AMN'),
('320','Nota relativa a bibliografia e índices internos ','Nota relativa a bibliografia e índices internos ',1,0,'','AMN'),
('330','Sumário ou resumo','Sumário ou resumo',1,0,'','AMN'),
('463','Nível de parte','Nível de parte',1,0,'','AMN'),
('500','Título Uniforme','Título Uniforme',1,0,'','AMN'),
('510','Título paralelo','Título paralelo',1,0,'','AMN'),
('518','Título na grafia actualizada','Título na grafia actualizada',1,0,'','AMN'),
('540','Título adicionado pelo catalogador','Título adicionado pelo catalogador',1,0,'','AMN'),
('541','Título traduzido pelo catalogador','Título traduzido pelo catalogador',1,0,'','AMN'),
('600','Nome de pessoa usado como assunto','Nome de pessoa usado como assunto',1,0,'','AMN'),
('601','Nome de colectividade usado como assunto','Nome de colectividade usado como assunto',1,0,'','AMN'),
('602','Nome de família usado como assunto','Nome de família usado como assunto',1,0,'','AMN'),
('604','Autor/título usado como assunto ','Autor/título usado como assunto ',1,0,'','AMN'),
('605','Título usado como assunto','Título usado como assunto',1,0,'','AMN'),
('606','Nome comum usado como assunto','Nome comum usado como assunto',1,0,'','AMN'),
('607','Nome geográfico usado como assunto','Nome geográfico usado como assunto',1,0,'','AMN'),
('610','Termos de indexação não controlados','Termos de indexação não controlados',1,0,'','AMN'),
('620','Acesso pelo local','Acesso pelo local',1,0,'','AMN'),
('675','Classificação Decimal Universal (CDU)','Classificação Decimal Universal (CDU)',1,0,'','AMN'),
('676','Classificação Decimal Dewey (CDD)','Classificação Decimal Dewey (CDD)',1,0,'','AMN'),
('680','Classificação da Biblioteca do Congresso','Classificação da Biblioteca do Congresso',1,0,'','AMN'),
('686','Outras classificações numéricas','Outras classificações numéricas',1,0,'','AMN'),
('700','Nome de autor-pessoa física (responsabilidade principal)','Nome de autor-pessoa física (responsabilidade principal)',0,0,'','AMN'),
('701','Nome de autor-pessoa física (co-responsabilidade principal)','Nome de autor-pessoa física (co-responsabilidade principal)',1,0,'','AMN'),
('702','Nome de autor-pessoa física (responsabilidade secundária)','Nome de autor-pessoa física (responsabilidade secundária)',1,0,'','AMN'),
('710','Nome de colectividade-autor (responsabilidade principal)','Nome de colectividade-autor (responsabilidade principal)',0,0,'','AMN'),
('711','Nome de colectividade-autor (co-responsabilidade principal)','Nome de colectividade-autor (co-responsabilidade principal)',1,0,'','AMN'),
('712','Nome de colectividade-autor (responsabilidade secundária)','Nome de colectividade-autor (responsabilidade secundária)',1,0,'','AMN'),
('801','Fonte de origem','Fonte de origem',1,0,'','AMN'),
('856','Localização e acesso electrónico ','Localização e acesso electrónico ',1,0,'','AMN'),
('990','Elementos KOHA','Elementos KOHA',0,0,'','AMN'),
('994','Estado da catalogação','Estado da catalogação',0,0,'','AMN'),
('995','Localização e informação dos exemplares','Localização e informação dos exemplares',1,1,'','AMN'),
('000','Etiqueta do registo','Etiqueta do registo',0,1,'','ANL'),
('001','Identificador de registo','Identificador de registo',0,1,'','ANL'),
('090','System Control Numbers (Koha)','System Control Numbers (Koha)',0,0,'','ANL'),
('100','Dados gerais de processamento','Dados gerais de processamento',0,0,'','ANL'),
('101','Língua de publicação','Língua de publicação',0,0,'','ANL'),
('102','País de publicação','País de publicação',0,0,'','ANL'),
('200','Titulo e menção de responsabilidade','Titulo e menção de responsabilidade',0,1,'','ANL'),
('210','Publicação','Publicação',0,0,'','ANL'),
('215','Descrição física ','Descrição física ',0,0,'','ANL'),
('300','Notas gerais ','Notas gerais ',0,0,'','ANL'),
('327','Nota de conteúdo','Nota de conteúdo',0,0,'','ANL'),
('330','Sumário ou Resumo','Sumário ou Resumo',0,0,'','ANL'),
('463','Nível de parte (artigos)','Nível de parte (artigos)',0,0,'','ANL'),
('500','Título uniforme','Título uniforme',0,0,'','ANL'),
('501','Título colectivo uniforme','Título colectivo uniforme',0,0,'','ANL'),
('517','Outras variantes do título','Outras variantes do título',1,0,'','ANL'),
('600','Nome de pessoa usado como assunto','Nome de pessoa usado como assunto',1,0,'','ANL'),
('601','Nome de colectividade usado como assunto','Nome de colectividade usado como assunto',1,0,'','ANL'),
('606','Nome comum usado como assunto','Nome comum usado como assunto',1,0,'','ANL'),
('610','Termos não controlados','Termos não controlados',1,0,'','ANL'),
('686','Outra Classificação','Outra Classificação',1,0,'','ANL'),
('700','Autor principal','Autor principal',0,0,'','ANL'),
('701','Autor co-responsavel','Autor co-responsavel',1,0,'','ANL'),
('702','Autor secundário','Autor secundário',1,0,'','ANL'),
('710','Autor entidade principal','Autor entidade principal',0,0,'','ANL'),
('711','Autor entidade co-responsavel','Autor entidade co-responsavel',1,0,'','ANL'),
('712','Autor entidade secundário','Autor entidade secundário',1,0,'','ANL'),
('801','Fonte de origem','Fonte de origem',0,0,'','ANL'),
('830','Notas gerais do catalogador','Notas gerais do catalogador',0,0,'','ANL'),
('856','Localização e acesso electrónico ','Localização e acesso electrónico ',1,0,'','ANL'),
('990','Elementos KOHA','Elementos KOHA',0,0,'','ANL'),
('994','Estado da catalogação','Estado da catalogação',0,0,'','ANL'),
('995','Localização e informação dos exemplares','Localização e informação dos exemplares',1,0,'','ANL'),
('000','Etiqueta do registo','Etiqueta do registo',0,1,'','MNL'),
('013','Número internacional ISMN','Número internacional ISMN',1,0,'','MNL'),
('016','Número internacional ISRC','Número internacional ISRC',1,0,'','MNL'),
('020','Número da bibliografia nacional','Número da bibliografia nacional',0,0,'','MNL'),
('021','Número do Depósito Legal','Número do Depósito Legal',0,0,'','MNL'),
('071','Número do Editor','Número do Editor',1,0,'','MNL'),
('090','System Control Numbers (Koha)','System Control Numbers (Koha)',0,0,'','MNL'),
('100','Dados gerais de processamento','Dados gerais de processamento',0,0,'','MNL'),
('101','Língua de publicação','Língua de publicação',0,0,'','MNL'),
('102','País de publicação','País de publicação',0,0,'','MNL'),
('200','Titulo e menção de responsabilidade','Titulo e menção de responsabilidade',1,1,'','MNL'),
('205','Menção da edição','Menção da edição',0,0,'','MNL'),
('208','Música impressa','Música impressa',0,0,'','MNL'),
('210','Publicação','Publicação',0,0,'','MNL'),
('215','Descrição física ','Descrição física ',0,0,'','MNL'),
('225','Colecção ','Colecção ',0,0,'','MNL'),
('230','Recursos electrónicos','Recursos electrónicos',1,0,'','MNL'),
('300','Notas gerais ','Notas gerais ',0,0,'','MNL'),
('301','Nota relativa a números de identificação','Nota relativa a números de identificação',1,0,'','MNL'),
('305','Nota relativa à edição da publicação','Nota relativa à edição da publicação',0,0,'','MNL'),
('322','Nota relativa a responsáveis artisticos e técnicos','Nota relativa a responsáveis artisticos e técnicos',1,0,'','MNL'),
('323','Nota relativa ao elenco','Nota relativa ao elenco',1,0,'','MNL'),
('327','Nota de conteúdo','Nota de conteúdo',1,0,'','MNL'),
('330','Sumário ou Resumo','Sumário ou Resumo',1,0,'','MNL'),
('336','Nota relativa ao tipo de ficheiro','Nota relativa ao tipo de ficheiro',1,0,'','MNL'),
('337','Nota relativa a pormenores técnicos','Nota relativa a pormenores técnicos',1,0,'','MNL'),
('500','Título uniforme','Título uniforme',0,0,'','MNL'),
('501','Título colectivo uniforme','Título colectivo uniforme',0,0,'','MNL'),
('517','Outras variantes do título','Outras variantes do título',1,0,'','MNL'),
('600','Nome de pessoa usado como assunto','Nome de pessoa usado como assunto',1,0,'','MNL'),
('601','Nome de colectividade usado como assunto','Nome de colectividade usado como assunto',1,0,'','MNL'),
('606','Nome comum usado como assunto','Nome comum usado como assunto',1,0,'','MNL'),
('610','Termos não controlados','Termos não controlados',1,0,'','MNL'),
('675','CDU','CDU',1,0,'','MNL'),
('686','Outra Classificação','Outra Classificação',1,0,'','MNL'),
('700','Autor principal','Autor principal',0,0,'','MNL'),
('701','Autor co-responsavel','Autor co-responsavel',1,0,'','MNL'),
('702','Autor secundário','Autor secundário',1,0,'','MNL'),
('710','Autor entidade principal','Autor entidade principal',0,0,'','MNL'),
('711','Autor entidade co-responsavel','Autor entidade co-responsavel',1,0,'','MNL'),
('712','Autor entidade secundário','Autor entidade secundário',1,0,'','MNL'),
('801','Fonte de origem','Fonte de origem',0,0,'','MNL'),
('830','Notas gerais do catalogador','Notas gerais do catalogador',0,0,'','MNL'),
('856','Localização e acesso electrónico ','Localização e acesso electrónico ',1,0,'','MNL'),
('990','Elementos KOHA','Elementos KOHA',0,0,'','MNL'),
('994','Estado da catalogação','Estado da catalogação',0,0,'','MNL'),
('995','Localização e informação dos exemplares','Localização e informação dos exemplares',1,0,'','MNL'),
('000','Etiqueta do registo','Etiqueta do registo',0,1,'','MON'),
('001','Identificador do registo','Identificador do registo',0,0,'','MON'),
('005','Identificador da versão','Identificador da versão',0,0,'','MON'),
('010','Número internacional normalizado dos livros (ISBN)','Número internacional normalizado dos livros (ISBN)',1,0,'','MON'),
('012','Identificador da impressão ','Identificador da impressão',1,0,'','MON'),
('021','Número do Depósito Legal','Número do Depósito Legal',1,0,'','MON'),
('090','System Control Numbers (Koha)','System Control Numbers (Koha)',0,0,'','MON'),
('100','Dados gerais de processamento','Dados gerais de processamento',0,1,'','MON'),
('101','Língua de publicação','Língua de publicação',0,0,'Lingua','MON'),
('102','Pais de publicação ou produção','Pais de publicação ou produção',0,0,'Pais','MON'),
('105','Campo de dados codificados: livros','Campo de dados codificados: livros',0,0,'','MON'),
('106','Campo de dados codificados: material textual','Campo de dados codificados: material textual',0,0,'','MON'),
('141','Características específicas do exemplar','Características específicas do exemplar',1,0,'','MON'),
('200','Titulo e menção de responsabilidade','Titulo e menção de responsabilidade',0,0,'','MON'),
('205','Menção da edição','Menção da edição',1,0,'','MON'),
('210','Publicação, Distribuição, etc. ','Publicação, Distribuição, etc. ',1,0,'','MON'),
('215','Descrição física ','Descrição física ',1,0,'','MON'),
('225','Coleção ','Coleção ',1,0,'','MON'),
('300','Notas gerais ','Notas gerais ',1,0,'','MON'),
('301','Notas relativas a números de identificação ','Notas relativas a números de identificação ',1,0,'','MON'),
('302','Notas relativas a informação codificada ','Notas relativas a informação codificada ',1,0,'','MON'),
('303','Notas gerais relativas a informação descritiva ','Notas gerais relativas a informação descritiva ',1,0,'','MON'),
('304','Notas relativas a título e menção de responsabilidade ','Notas relativas a título e menção de responsabilidade ',1,0,'','MON'),
('305','Notas relativas à edição e história bibliográfica da publicação ','Notas relativas à edição e história bibliográfica da publicação ',1,0,'','MON'),
('306','Notas relativas a publicação, distribuição, etc. ','Notas relativas a publicação, distribuição, etc. ',1,0,'','MON'),
('307','Notas relativas a descrição física ','Notas relativas a descrição física ',1,0,'','MON'),
('308','Notas relativas à coleção','Notas relativas à coleção',1,0,'','MON'),
('310','Notas relativas à encadernação e modalidade de aquisição ','Notas relativas à encadernação e modalidade de aquisição ',1,0,'','MON'),
('311','Notas relativas a campos de entradas relacionadas ','Notas relativas a campos de entradas relacionadas ',1,0,'','MON'),
('312','Notas relativas a títulos relacionados ','Notas relativas a títulos relacionados ',1,0,'','MON'),
('313','Notas relativas a acesso por assunto ','Notas relativas a acesso por assunto ',1,0,'','MON'),
('314','Notas relativas a responsabilidade intelectual ','Notas relativas a responsabilidade intelectual ',1,0,'','MON'),
('315','Notas relativas a informação específica sobre alguns tipos de materiais (ou tipo de publicação)','Notas relativas a informação específica sobre alguns tipos de materiais (ou tipo de publicação)',1,0,'','MON'),
('316','Nota relativa ao exemplar catalogado (em mão) ','Nota relativa ao exemplar catalogado (em mão) ',1,0,'','MON'),
('317','Nota de proveniência ','Nota de proveniência ',1,0,'','MON'),
('318','Nota de intervenção ','Nota de intervenção ',1,0,'','MON'),
('320','Nota relativa a bibliografia e índices internos ','Nota relativa a bibliografia e índices internos ',1,0,'','MON'),
('321','Nota relativa a indíces, resumos de autor e referências externas ','Nota relativa a indíces, resumos de autor e referências externas ',1,0,'','MON'),
('324','Nota de versão original','Nota de versão original',0,0,'','MON'),
('325','Nota de reprodução','Nota de reprodução',1,0,'','MON'),
('327','Nota de conteúdo ','Nota de conteúdo ',1,0,'','MON'),
('328','Nota de dissertação ou tese','Nota de dissertação ou tese',1,0,'','MON'),
('330','Sumário ou Resumo','Sumário ou Resumo',1,0,'','MON'),
('345','Nota informativa sobre aquisição','Nota informativa sobre aquisição',0,0,'','MON'),
('410','Coleção','Coleção',1,0,'','MON'),
('421','Suplemento de','Suplemento de',1,0,'','MON'),
('422','Filiação do suplemento','Filiação do suplemento',1,0,'','MON'),
('423','Publicado com','Publicado com',1,0,'','MON'),
('437','Separado de','Separado de',1,0,'','MON'),
('451','Outra edição no mesmo suporte','Outra edição no mesmo suporte',1,0,'','MON'),
('452','Edição em suporte diferente','Edição em suporte diferente',1,0,'','MON'),
('453','Traduzido como','Traduzido como',1,0,'','MON'),
('454','Tradução de','Tradução de',1,0,'','MON'),
('481','Também encadernado neste volume','Também encadernado neste volume',1,0,'','MON'),
('482','Encadernado com','Encadernado com',1,0,'','MON'),
('500','Título Uniforme','Título Uniforme',1,0,'','MON'),
('503','Cabeçalho convencional uniforme','Cabeçalho convencional uniforme',1,0,'','MON'),
('510','Título paralelo','Título paralelo',1,0,'','MON'),
('512','Título da capa','Título da capa',1,0,'','MON'),
('517','Outras variantes do título','Outras variantes do título',1,0,'','MON'),
('518','Título na grafia actualizada','Título na grafia actualizada',1,0,'','MON'),
('532','Título desenvolvido','Título desenvolvido',1,0,'','MON'),
('541','Título traduzido pelo catalogador','Título traduzido pelo catalogador',1,0,'','MON'),
('600','Nome de pessoa usado como assunto','Nome de pessoa usado como assunto',1,0,'','MON'),
('601','Nome de colectividade usado como assunto','Nome de colectividade usado como assunto',1,0,'','MON'),
('604','Autor/título usado como assunto ','Autor/título usado como assunto ',1,0,'','MON'),
('605','Título usado como assunto','Título usado como assunto',1,0,'','MON'),
('606','Nome comum usado como assunto','Nome comum usado como assunto',1,0,'','MON'),
('607','Nome geográfico usado como assunto','Nome geográfico usado como assunto',1,0,'','MON'),
('610','Termos de indexação não controlados','Termos de indexação não controlados',1,0,'','MON'),
('620','Acesso pelo local','Acesso pelo local',1,0,'','MON'),
('675','Classificação Decimal Universal (CDU)','Classificação Decimal Universal (CDU)',1,0,'','MON'),
('676','Classificação Decimal Dewey (CDD)','Classificação Decimal Dewey (CDD)',1,0,'','MON'),
('680','Classificação da Biblioteca do Congresso','Classificação da Biblioteca do Congresso',1,0,'','MON'),
('686','Outras classificações numéricas','Outras classificações numéricas',1,0,'','MON'),
('700','Nome de autor-pessoa física (responsabilidade principal)','Nome de autor-pessoa física (responsabilidade principal)',0,0,'','MON'),
('701','Nome de autor-pessoa física (co-responsabilidade principal)','Nome de autor-pessoa física (co-responsabilidade principal)',1,0,'','MON'),
('702','Nome de autor-pessoa física (responsabilidade secundária)','Nome de autor-pessoa física (responsabilidade secundária)',1,0,'','MON'),
('710','Nome de colectividade-autor (responsabilidade principal)','Nome de colectividade-autor (responsabilidade principal)',0,0,'','MON'),
('711','Nome de colectividade-autor (co-responsabilidade principal)','Nome de colectividade-autor (co-responsabilidade principal)',1,0,'','MON'),
('712','Nome de colectividade-autor (responsabilidade secundária)','Nome de colectividade-autor (responsabilidade secundária)',1,0,'','MON'),
('720','Nome de família (responsabilidade principal)','Nome de família (responsabilidade principal)',0,0,'','MON'),
('721','Nome de família (co-responsabilidade principal)','Nome de família (co-responsabilidade principal)',1,0,'','MON'),
('722','Nome de família (responsabilidade secundária)','Nome de família (responsabilidade secundária)',1,0,'','MON'),
('801','Fonte de origem','Fonte de origem',1,0,'','MON'),
('856','Localização e acesso electrónico ','Localização e acesso electrónico ',1,0,'','MON'),
('990','Elementos KOHA','Elementos KOHA',0,0,'','MON'),
('994','Estado da catalogação','Estado da catalogação',0,0,'','MON'),
('995','Localização e informação dos exemplares','Localização e informação dos exemplares',0,1,'','MON'),
('000','Etiqueta do registo','Etiqueta do registo',0,1,'','PER'),
('001','Identificador de registo','Identificador de registo',0,1,'','PER'),
('011','Número ISSN','Número  ISSN',1,0,'','PER'),
('021','Número do Depósito Legal','Número do Depósito Legal',0,0,'','PER'),
('040','Número CODEN ','Número CODEN',1,0,'','PER'),
('090','System Control Numbers (Koha)','System Control Numbers (Koha)',0,0,'','PER'),
('100','Dados gerais de processamento','Dados gerais de processamento',0,0,'','PER'),
('101','Língua de publicação','Língua de publicação',0,0,'','PER'),
('102','País de publicação','País de publicação',0,0,'','PER'),
('200','Titulo e menção de responsabilidade','Titulo e menção de responsabilidade',1,1,'','PER'),
('207','Numeração','Numeração',0,0,'','PER'),
('210','Publicação','Publicação',0,0,'','PER'),
('215','Descrição física ','Descrição física ',0,0,'','PER'),
('225','Colecção ','Colecção ',0,0,'','PER'),
('300','Notas gerais ','Notas gerais ',0,0,'','PER'),
('303','Nota relativa à informação descritiva','Nota relativa à informação descritiva',1,0,'','PER'),
('326','Nota de Periodicidade','Nota de Periodicidade',0,0,'','PER'),
('327','Nota de conteúdo','Nota de conteúdo',0,0,'','PER'),
('330','Sumário ou Resumo','Sumário ou Resumo',0,0,'','PER'),
('500','Título uniforme','Título uniforme',0,0,'','PER'),
('501','Título colectivo uniforme','Título colectivo uniforme',0,0,'','PER'),
('517','Outras variantes do título','Outras variantes do título',1,0,'','PER'),
('520','Título anterior','Título anterior',1,0,'','PER'),
('600','Nome de pessoa usado como assunto','Nome de pessoa usado como assunto',1,0,'','PER'),
('601','Nome de colectividade usado como assunto','Nome de colectividade usado como assunto',1,0,'','PER'),
('606','Nome comum usado como assunto','Nome comum usado como assunto',1,0,'','PER'),
('610','Termos não controlados','Termos não controlados',1,0,'','PER'),
('675','CDU','CDU',1,0,'','PER'),
('686','Outra Classificação','Outra Classificação',1,0,'','PER'),
('700','Autor principal','Autor principal',0,0,'','PER'),
('701','Autor co-responsavel','Autor co-responsavel',1,0,'','PER'),
('702','Autor secundário','Autor secundário',1,0,'','PER'),
('710','Autor entidade principal','Autor entidade principal',0,0,'','PER'),
('711','Autor entidade co-responsavel','Autor entidade co-responsavel',1,0,'','PER'),
('712','Autor entidade secundário','Autor entidade secundário',1,0,'','PER'),
('801','Fonte de origem','Fonte de origem',0,0,'','PER'),
('830','Notas gerais do catalogador','Notas gerais do catalogador',0,0,'','PER'),
('856','Localização e acesso electrónico ','Localização e acesso electrónico ',1,0,'','PER'),
('990','Elementos KOHA','Elementos KOHA',0,0,'','PER'),
('994','Estado da catalogação','Estado da catalogação',0,0,'','PER'),
('995','Localização e informação dos exemplares','Localização e informação dos exemplares',1,0,'','PER'),
('000','Etiqueta do registo','Etiqueta do registo',0,1,'','PESP'),
('010','ISBN','ISBN',0,0,'','PESP'),
('020','Número da bibliografia nacional','Número da bibliografia nacional',0,0,'','PESP'),
('021','Número do Depósito Legal','Número do Depósito Legal',0,0,'','PESP'),
('090','System Control Numbers (Koha)','System Control Numbers (Koha)',0,0,'','PESP'),
('100','Dados gerais de processamento','Dados gerais de processamento',0,0,'','PESP'),
('101','Língua de publicação','Língua de publicação',0,0,'','PESP'),
('102','País de publicação','País de publicação',0,0,'','PESP'),
('200','Titulo e menção de responsabilidade','Titulo e menção de responsabilidade',1,1,'','PESP'),
('210','Publicação','Publicação',0,0,'','PESP'),
('215','Descrição física ','Descrição física ',0,0,'','PESP'),
('300','Notas gerais ','Notas gerais ',0,0,'','PESP'),
('305','Nota relativa à edição da publicação','Nota relativa à edição da publicação',0,0,'','PESP'),
('322','Nota relativa a responsáveis artisticos e técnicos','Nota relativa a responsáveis artisticos e técnicos',1,0,'','PESP'),
('323','Nota relativa ao elenco','Nota relativa ao elenco',1,0,'','PESP'),
('327','Nota de conteúdo','Nota de conteúdo',1,0,'','PESP'),
('330','Sumário ou Resumo','Sumário ou Resumo',1,0,'','PESP'),
('500','Título uniforme','Título uniforme',0,0,'','PESP'),
('501','Título colectivo uniforme','Título colectivo uniforme',0,0,'','PESP'),
('517','Outras variantes do título','Outras variantes do título',1,0,'','PESP'),
('600','Nome de pessoa usado como assunto','Nome de pessoa usado como assunto',1,0,'','PESP'),
('601','Nome de colectividade usado como assunto','Nome de colectividade usado como assunto',1,0,'','PESP'),
('606','Nome comum usado como assunto','Nome comum usado como assunto',1,0,'','PESP'),
('610','Termos não controlados','Termos não controlados',1,0,'','PESP'),
('675','CDU','CDU',1,0,'','PESP'),
('686','Outra Classificação','Outra Classificação',1,0,'','PESP'),
('700','Autor principal','Autor principal',0,0,'','PESP'),
('701','Autor co-responsavel','Autor co-responsavel',1,0,'','PESP'),
('702','Autor secundário','Autor secundário',1,0,'','PESP'),
('710','Autor entidade principal','Autor entidade principal',0,0,'','PESP'),
('711','Autor entidade co-responsavel','Autor entidade co-responsavel',1,0,'','PESP'),
('712','Autor entidade secundário','Autor entidade secundário',1,0,'','PESP'),
('801','Fonte de origem','Fonte de origem',0,0,'','PESP'),
('830','Notas gerais do catalogador','Notas gerais do catalogador',0,0,'','PESP'),
('856','Localização e acesso electrónico ','Localização e acesso electrónico ',1,0,'','PESP'),
('990','Elementos KOHA','Elementos KOHA',0,0,'','PESP'),
('994','Estado da catalogação','Estado da catalogação',0,0,'','PESP'),
('995','Localização e informação dos exemplares','Localização e informação dos exemplares',1,0,'','PESP');

/*!40000 ALTER TABLE `marc_tag_structure` ENABLE KEYS */;
UNLOCK TABLES;

/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
